alphagov/verify-self-service

manifest.yml

Add a minimal manifest for deployment to PaaS.

NDRHGGrk: Add minimal PaaS manifest

---

spec/rails_helper.rb

This hides it so the test results are cleaner.
Before:
After:

BAU: Capybara spins up the puma server with its output

---

.gitignore
app/controllers/home_controller.rb
app/helpers/home_helper.rb
app/views/home/index.html.erb
config/routes.rb
lib/tasks/acceptance_tests.rake
spec/acceptance/visit_home_controller_acceptance_spec.rb
spec/acceptance_helper.rb
spec/controllers/home_controller_spec.rb
spec/system/visit_home_controller_spec.rb

* Replaced Home view and Controller for a stable entry point for testing.
* Added Rake task for acceptance tests.
* Added basic acceptance test that visits the Home page.
* Added acceptance helper to configure the acceptance test environment.
* Filtered out acceptance tests so they do not run under when not required.
* Replaced system test for home page.
Co-authored-by: Olakunle Jegede <olakunle.jegede@digital.cabinet-office.gov.uk>
This is a new branch with all the work from the old one on top of master after my git-fu spectacularly failed me.

8wA933sS: Add Acceptance tests

---

Procfile

This will run the database migrations on start up when deployed to PaaS

7kgfqv0Q: Add Procfile to run database migrations on PaaS

---

.gitignore
Gemfile
Gemfile.lock
config/database.yml
manifest.yml

Update application config and CF manifest to use a Postgres backing
service that has been setup in GOV.UK PaaS.
co-authored-by: Olakunle Jegede <olakunle.jegede@digital.cabinet-office.gov.uk>

omtujEyR: Use PAAS backing service

---

app/models/aggregate.rb
app/models/certificate.rb
spec/models/certificate_spec.rb

Currently, just provides an association to events, but we will extend it
later with some extras (e.g. protection against out of event saving).

VavuzB9e: add an `Aggregate` class

---

config/initializers/assets.rb

When deployed, the govuk-frontend assets are missing. We need
to explicitly add them to the asset pipeline.
Caused by https://github.com/rails/rails/issues/29563

0xDiu18N: Fix govuk assets loading

---

Rakefile
config/initializers/assets.rb
lib/tasks/copy_govuk_dependencies.rake

In the previous attempt the assets got copied correctly but included digest.
Given the files are referenced by a library, that wouldn't work.
Therefore adding a new Rake task to handle copying the dependencies over.
[Known issue](https://github.com/rails/rails/issues/29563)

0xDiu18N: Fix assets

---

Procfile

We shouldn't need this file. It runs db:migration (again) which we don't want to
do when deployed.

BAU: Remove Procfile

---

spec/models/certificate_spec.rb
spec/models/upload_certificate_event_spec.rb
spec/support/certificate_support.rb
spec/support/pki.rb
spec/system/user_visits_events_page_spec.rb
spec/system/visit_upload_page_spec.rb

This PR introduces optional arguments for `PKI` to control the content of the certificate. 
This should allow for easy extensibility.

JEayxx4g: improve interface of PKI support class

---

app/views/certificates/index.html.erb

We should be using link_to for all local links as this will ensure that
the any base paths are added if they're needed.

bau: use a link helper for stray link

---

app/controllers/certificates_controller.rb
app/controllers/components_controller.rb
app/models/component.rb
app/views/certificates/_certificates_table.html.erb
app/views/components/index.html.erb
app/views/components/show.html.erb
db/migrate/20190424150803_add_enabled_to_certificates.rb
db/schema.rb
spec/system/visit_component_show_spec.rb
spec/system/visit_index_page_spec.rb
spec/system/visit_upload_page_spec.rb

This is initial PR for the ticket: [model-signing-certificate-rotation-in-the-app](https://trello.com/c/ee2PV5rg/348-model-signing-certificate-rotation-in-the-app). 
* Added a boolean enabled column to the certificates table that is set true by default.
* In the component view show separate tables for 'Signing certs (enabled)' and 'Signing certs (disabled)'
* Provide buttons for the entries in those tables to update the certificate enabled setting.
* Add tests to exercise these buttons.
Todo:
* Create events for enabling and disabling the certificates
* Drive changes to the event status on the certificate from the events.

ee2PV5rg - model signing cert rotation

---

config/application.rb

By default rails wraps invalid inputs with
`<div class="field_with_errors">` we have our own way of
styling errors using Design System, so we don't need this behaviour.
This commit disables adding the wrapper.

BAU: Fix validation styles

---

app/controllers/certificates_controller.rb
app/models/disable_signing_certificate_event.rb
app/models/enable_signing_certificate_event.rb
app/models/signing_certificate_event.rb
spec/models/disable_signing_certificate_event_spec.rb
spec/models/enable_signing_certificate_event_spec.rb

- Create events for enabling and disabling certificates.
#TODO in next PR:
- Replace `certificate#update` with separate `enable` and `disable` actions.
- Trigger publish event when a signing certificate is enabled or disabled.
Co-authored-by: Olakunle Jegede <olakunle.jegede@digital.cabinet-office.gov.uk>

Eox5bz3c - events for enabling and disabling signing certificates

---

app/controllers/certificates_controller.rb
app/models/certificate.rb
app/models/component.rb
app/models/replace_encryption_certificate_event.rb
app/models/upload_certificate_event.rb
app/views/certificates/_certificates_table.html.erb
app/views/certificates/new.html.erb
app/views/components/show.html.erb
config/initializers/constants/vss_constants.rb
db/migrate/20190507132826_add_encryption_certificate_to_components.rb
db/schema.rb
spec/models/certificate_spec.rb
spec/models/component_spec.rb
spec/models/disable_signing_certificate_event_spec.rb
spec/models/enable_signing_certificate_event_spec.rb
spec/models/replace_encryption_certificate_event_spec.rb
spec/models/upload_certificate_event_spec.rb
spec/system/user_visits_events_page_spec.rb
spec/system/visit_component_show_spec.rb

[This](https://trello.com/c/ZfIp1eQu/376-assign-encryption-certificate-to-component-on-upload) is first of a line of PR's for [Model encryption certificate rotation](https://trello.com/c/WCo3BuKn/347-model-encryption-certificate-rotation-in-the-app)
**What**
- This enables an encryption certificate to be assigned with a Component via a belongs_to association on the component.
- ReplaceEncryptionCertificateEvent is used to carry out this assignment.
- Since this happens at the time a new encryption certificate is created it follows that, this certificate becomes the assigned one.
- The associated encryption certificate is displayed on the Show view
**To do**
- To show a list of the previous encryption certs and to be able to replace the ‘current’ encryption certificate with a previous …

Wco3bukn/zfip1equ: assign encryption cert to component on upload

---

app/controllers/events_controller.rb
app/models/event.rb
app/views/events/index.html.erb

- events are ordered by date now (created_at)
- event details are not expanded by default anymore (too much content)
- added miliseconds on the timestamp

BAU: Fix event ordering

---

app/models/component.rb
app/models/publish_services_metadata_event.rb
spec/models/component_spec.rb
spec/models/publish_services_event_metadata_spec.rb

Review commit by commit.
1. Changed the logic so that we always generate the same filename for the metadata file.
2. Currently, we're converting the metadata object to a json and storing it.
We should only convert the data to JSON when we export them. Internally we should
use native hashes.
This PR:
- renames the json_data to metadata object
- removes the JSON conversion from the component
- moves the JSON conversion to the PublishServicesMetadataEvent to the point when it generates
the JSON file.

BAU: Refactor the publish event

---

app/controllers/components_controller.rb
app/models/component.rb
app/models/new_component_event.rb
app/models/publish_services_metadata_event.rb
app/views/components/new.html.erb
db/migrate/20190520094157_add_entity_id_to_components.rb
db/schema.rb
spec/models/certificate_spec.rb
spec/models/component_spec.rb
spec/models/new_component_event_spec.rb
spec/models/replace_encryption_certificate_event_spec.rb
spec/models/upload_certificate_event_spec.rb
spec/system/user_visits_events_page_spec.rb
spec/system/visit_component_new_spec.rb
spec/system/visit_component_show_spec.rb
spec/system/visit_upload_page_spec.rb

Components of type MSA must have an entityId. We should be able to set this in the frontend and it should be exported with the configuration metadata to S3.
Why do we need it?
We need to be able to retrieve certificates that are used by the MSA given the entityId that it identifies itself with. We therefore need to able to configure this and make it available to the hub config service.

Thxe01tp: Add entity_id to MSA components

---

app/models/new_component_event.rb

Clicking the Create component button on /components/new i.e the
**Upload your component page** currently generates an error due using
update_attribute changing to assign_attributes fixes this error.

BAU: Setting Entity_id to nil when not msa

---

Gemfile
Gemfile.lock
app/controllers/components_controller.rb
app/models/component.rb
app/models/new_component_event.rb
app/models/new_msa_component_event.rb
app/models/new_service_event.rb
app/models/service.rb
db/migrate/20190528114026_create_services.rb
db/schema.rb
spec/factories/component.rb
spec/factories/service.rb
spec/models/component_spec.rb
spec/models/msa_component.rb
spec/models/service_spec.rb
spec/support/factory_bot.rb

This adds the (connected) service model. Each service:
- Can only have a maximum of 2 components
- Cannot have components of the same component_type
- Cannot not have both a VSP and a SP component type
- The `entity_id` is unique across all services
- Add factory_bot_rails gem
- Create a MSA specific component in order to make it easier to represent the relationship components and services.
https://trello.com/c/vK1m0UlX/391-add-connected-service-model-to-self-service-app

Create Service Model

---

app/controllers/services_controller.rb
app/models/component.rb
app/models/concerns/component_concern.rb
app/models/msa_component.rb
app/models/new_msa_component_event.rb
app/models/new_service_event.rb
app/models/service.rb
app/models/sp_component.rb
app/views/msa_components/_all_msa_components.html.erb
app/views/msa_components/show.html.erb
app/views/services/index.html.erb
app/views/services/list/_services_table.html.erb
app/views/services/new.html.erb
app/views/sp_components/_all_sp_components.html.erb
app/views/sp_components/show.html.erb
config/routes.rb
db/migrate/20190607154410_correct_services_table_columns.rb
db/schema.rb
spec/factories/service.rb
spec/models/msa_component.rb
spec/models/service_spec.rb
spec/rails_helper.rb
spec/system/shared_examples/new_component_service.rb
spec/system/visit_msa_service_new_spec.rb
spec/system/visit_sp_service_new_spec.rb

Review after:
This adds the views and controller for interacting with Services. Users can now add Connected Services to a component.
The Service previously had a connection to the older Component model which is now abstract, so the `component_id` column was renamed to `sp_component_id` in order to bring it into line with the recent model changes.
What is a component without services? It's like Alexander without his elephants . . .
https://trello.com/c/VL3EbxHV/424-add-connected-service-component-relationship-through-the-front-end

Add Connected Services views and controller

---

app/models/component.rb
app/models/msa_component.rb
app/models/sp_component.rb
spec/models/component_spec.rb

- Metadata now also includes `connected_services` to adhere to: https://github.com/alphagov/verify-hub/blob/master/hub/config/src/test/resources/remote-test-config.json
Co-authored-by: Brendan Butler <brendan.butler@digital.cabinet-office.gov.uk>

NtRhoDQ0: Update metadata schema to include services

---

app/models/certificate.rb
app/models/component.rb
app/models/publish_services_metadata_event.rb
spec/factories/events.rb
spec/models/component_spec.rb

We had previously made an incorrect assumption about the publishing of
the metadata. It should always be a the latest metadata for all
components regardless of type.
The component_spec should now show a complete example of the published
metadata structure.
Also removed some tests from component_spec which were already being
tested in other specs.

Correctly publish metadata

---

config/storage.yml

The bucket requires `server_side_encryption` header to be sent in the upload request so add this to the amazon config section.
https://trello.com/c/3VTpnx6M/466-create-user-and-roles-for-s3-access-in-staging

Add additional config for S3 file upload

---

app/models/certificate.rb
app/models/concerns/certificate_concern.rb
app/models/upload_certificate_event.rb
config/initializers/validators/certificate_validator.rb
spec/models/upload_certificate_event_spec.rb

The uploaded certs were stored as whatever the input was. This change makes sure
they are always saved as base64 encoded DERs to maintain the consistency.
Co-Authored-By: Brendan Butler <brendan.butler@digital.cabinet-office.gov.uk>

lv78wFsR: Sanitise certs when storing them

---

app/models/certificate.rb
app/models/component.rb
app/models/new_msa_component_event.rb
app/models/new_sp_component_event.rb
app/models/sp_component.rb
app/models/upload_certificate_event.rb
app/views/certificates/new.html.erb
app/views/certificates/new/_msa_cert.html.erb
app/views/certificates/new/_sp_cert.html.erb
app/views/sp_components/new.html.erb
config/initializers/constants/certificate_usage.rb
config/initializers/constants/component_type.rb
spec/factories/components.rb
spec/factories/events.rb
spec/models/certificate_spec.rb
spec/models/component_spec.rb
spec/models/disable_signing_certificate_event_spec.rb
spec/models/enable_signing_certificate_event_spec.rb
spec/models/new_sp_component_event_spec.rb
spec/models/replace_encryption_certificate_event_spec.rb
spec/models/upload_certificate_event_spec.rb
spec/support/component_support.rb
spec/system/shared_examples/show_component_page.rb
spec/system/user_visits_events_page_spec.rb
spec/system/visit_msa_component_show_spec.rb
spec/system/visit_sp_component_show_spec.rb

Split the CONSTANT module to the named modules to better reflect the meaning
and get rid of the `CONSTANTS` keyword.

BAU: Meaningful constants

---

Dockerfile
test.Dockerfile

This will be used on Fargate.
Also renamed the testing Dockerfile to `test.Dockerfile` which is still used for
acceptance tests.

3e3ArKCb: Create a dockerfile to run self-service

---

db/migrate/20190711143928_devise_create_users.rb
db/schema.rb

- Tiny PR to fix the migrations on the pipeline as `add_index :users, :reset_password_token` fails due to `reset_password_token` being commented out.

BAU: Fix db migrations

---

Dockerfile

Port 8080 is what is used in the AWS Fargate config so we need to expose that one instead.

Expose correct port

---

config/database.yml

We need to pass in the username, password etc into the database config for running in production to allow connection to the RDS DB in AWS.
https://trello.com/c/hwOQiG8U/560-add-self-service-app-user-to-db-in-staging

Update database config

---

Dockerfile

The app is failing to load the sign in page because the assets are not being compiled when the Docker image is built.

Precompile assets in the Dockerfile

---

config/environments/production.rb

The production assets are going to be served from CDN/S3, so adding the
required config flags.

LHhRXxEk: Add assets config in production

---

Dockerfile
config/environments/production.rb
lib/tasks/undigest_assets.rake

We need to make sure the assets hosted in S3 have the same name, therefore when compiling, we need to make sure they don't have the digest appended to their filename.

BAU: Fix assets

---

app/controllers/application_controller.rb
app/models/remote_authenticatable.rb
app/models/user.rb
app/views/devise/sessions/_mfa_form.erb
app/views/devise/sessions/_new_password_required_form.erb
app/views/devise/sessions/_sign_in_form.erb
app/views/devise/sessions/new.html.erb
app/views/profile/show.html.erb
config/initializers/remote_authenticatable.rb
config/initializers/services.rb
config/locales/en.yml
spec/controllers/session_controller_spec.rb
spec/system/visit_sign_in_spec.rb

_(please review commit by commit)_
- Removed traces of organisation attribute, as we don't use it
- Made the auth_challenge logic more generic
- Added support for NEW_PASSWORD_REQUIRED for new users logging in first time (new logic and view)
- Cleaned a few things up by removing unnecessary logic and complexity around passing user email using hidden forms 
- Stopped using the hidden field to pass back to Cognito but instead using the Cognito-provided value
- Removed the reset button
- Moved the login content to locales

Improve the auth flow and force new users to change password

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/mfa_enrolment.scss
app/controllers/mfa_controller.rb
app/controllers/users_controller.rb
app/helpers/user_info.rb
app/models/invite_user_form.rb
app/models/mfa_enrolment_form.rb
app/models/remote_authenticatable.rb
app/models/user.rb
app/views/devise/sessions/_mfa_form.erb
app/views/mfa/index.html.erb
app/views/users/invite.erb
config/initializers/remote_authenticatable.rb
config/locales/en.yml
config/routes.rb
spec/controllers/mfa_controller_spec.rb
spec/controllers/session_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/factories/users.rb
spec/models/invite_user_form_spec.rb
spec/models/mfa_enrolment_form_spec.rb
spec/models/new_sp_component_event_spec.rb
spec/rails_helper.rb
spec/system/sign_out_spec.rb
spec/system/visit_mfa_enrolment_spec.rb
spec/system/visit_sign_in_spec.rb

apologies for the size, it's best to be review commit by commit
This PR consists of (see the individual commits for more details):
- Some PR leftover refactors on the UsersController
- Removed the use of the Thread and replaced with RequestStore
- Removed references to `friendly name` for MFA
- Introduced the mfa-enrolment step for users without MFA set-up

HrPL2H6a: Allow users to enrol to MFA

---

app/controllers/admin/teams_controller.rb
app/models/new_team_event.rb
app/views/layouts/application.html.erb
config/initializers/constants/teams.rb
config/locales/en.yml
db/migrate/20190807134744_add_team_alias_to_teams.rb
db/schema.rb
spec/controllers/admin/teams_controller_spec.rb
spec/models/new_team_event_spec.rb
spec/support/cognito_support.rb
spec/system/visit_team_new_spec.rb

[Create group in cognito](https://trello.com/c/MqjCqcyS/578-create-a-group-in-cognito-when-a-team-is-created)
What
In Associate components with teams we introduced Teams. We now need to reflect the teams in Cognito as groups.
Why
So we can control user access effectively and securely.

Create group in cognito

---

config/routes.rb

The production build is broken as we restrict the `profile_path` to non-prod environment.
However, we started linking to the page from the main layout:
https://github.com/alphagov/verify-self-service/blob/fb3cd583cf1cd5eed195b1c4e21020730316baaa/app/views/layouts/application.html.erb#L57 meaning it now breaks.
I'm removing the route constraints as there's nothing sensitive at this moment.

BAU: Fix the staging deployment

---

app/views/devise/sessions/_mfa_form.erb
app/views/devise/sessions/_new_password_required_form.erb
app/views/devise/sessions/_sign_in_form.erb

From full-width to more reasonable sizes.
Before:
After:

BAU: Fix the input width

---

app/controllers/application_controller.rb
app/models/remote_authenticatable.rb
app/models/user.rb
app/models/user_timeout_event.rb
config/application.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/devise.rb
config/secrets.yml
spec/controllers/profile_controller_spec.rb
spec/factories/users.rb
spec/support/time_helpers.rb
spec/system/sign_out_spec.rb

Implement both the idle and absolute timeouts.
- The idle timeout should be 15 minutes (the session should be invalidated if the last activity was 15 minutes or more ago)
- The absolute timeout should be 90 minutes (the user needs to re-authenticate after 90 minutes of their initial login, regardless of their activity)
The values above should be configurable.
To comply with security standards and recommendations we should implement session timeouts - both idle and absolute timeouts. This will prevent potential hijackers from using existing sessions or gaining unauthorized access.

Added session expiry and inactivity expiry

---

app/views/msa_components/_all_msa_components.html.erb
app/views/msa_components/edit.html.erb
app/views/sp_components/_all_sp_components.html.erb
app/views/sp_components/edit.html.erb
config/environments/test.rb
config/locales/en.yml
spec/system/visit_msa_component_edit_spec.rb
spec/system/visit_sp_component_edit_spec.rb

1. Enabled the raise an exception on missing translations
2. Eight tests failed
3. Fixed them :allthethings:
Given we're now using the localized content it makes sense to raise an error when
it's missing. By default, it will not fail and put the key name instead.
Enabling this in the test env to highlight missing content during tests.

BAU: Fix missing translations

---

config/initializers/services.rb
lib/auth/cognito_chooser.rb
lib/auth/cognito_stub_client.rb

This PR refactors the stub cognito client stuff in to its own module and allows for switching between the stub client and real client.  Next part will be to wire something up in the front end which allows the switch and then to assume roles.  This will be done on the profiles controller.

Refactored stub client and allow client switching

---

app/controllers/msa_components_controller.rb
app/controllers/sp_components_controller.rb
app/models/new_msa_component_event.rb
app/models/new_sp_component_event.rb
app/views/msa_components/_all_msa_components.html.erb
app/views/msa_components/new.html.erb
app/views/shared/_component_environments.erb
app/views/sp_components/_all_sp_components.html.erb
app/views/sp_components/new.html.erb
config/initializers/constants/environment.rb
config/locales/en.yml
db/migrate/20190812105927_add_environment_to_sp_components.rb
db/migrate/20190812110003_add_environment_to_msa_components.rb
db/migrate/20190813161922_drop_users_table.rb
db/schema.rb
spec/factories/components.rb
spec/factories/events.rb
spec/models/certificate_spec.rb
spec/models/disable_signing_certificate_event_spec.rb
spec/models/enable_signing_certificate_event_spec.rb
spec/models/new_msa_component_event_spec.rb
spec/models/new_sp_component_event_spec.rb
spec/models/replace_encryption_certificate_event_spec.rb
spec/models/upload_certificate_event_spec.rb
spec/system/user_visits_events_page_spec.rb
spec/system/visit_msa_component_new_spec.rb
spec/system/visit_sp_component_new_spec.rb
spec/system/visit_upload_page_spec.rb

[first task of support multiple environments card](https://trello.com/c/SGmDAu9A/603-support-multiple-environments) which would make it easier to proceed on the rest
The self-service app will be running in production, but will allow changing the certs in both hub production and hub integration environments.
We need to make appropriate changes to support that.
**Components should have a new attribute identifying to which environment the component belongs.**
The environment attribute is a required value on components
The app supports multiple buckets to write to
When a change is made and the publish metadata event is triggered it generates the correct metadata and write it the correct bucket

Pcijgfac add new s3 environment field to components

---

.pre-commit-config.yaml
app/controllers/profile_controller.rb
app/policies/profile_controller_policy.rb
app/views/profile/show.html.erb
config/locales/en.yml
config/routes.rb
lib/auth/cognito_chooser.rb
lib/auth/cognito_stub_client.rb
pre-commit.sh
spec/controllers/profile_controller_spec.rb

A page (profile) where the dev users can assume different roles as defined in the previous card. We can assume multiple roles (check boxes).
This will enable us testing different roles.
This PR also has some small changes to pre-commit to help it run better and some tweaks to the previous backend work.

24HFwXaC Assume roles locally (frontend)

---

app/models/publish_services_metadata_event.rb
app/models/trigger_metadata_event_callback.rb
config/initializers/constants/environment.rb
config/initializers/services.rb
config/integration_storage.yml
config/secrets.yml
config/storage.yml
db/schema.rb
lib/tasks/acceptance_tests.rake
spec/models/publish_services_event_metadata_spec.rb

Aim: [The app supports multiple buckets to write to](https://trello.com/c/JUdG1LLL/613-self-service-supports-writing-to-multiple-s3-buckets)
Background:
Currently Self Service is already set up to be deployed to a staging environment and to write config to a staging s3 bucket.
We want to extend Self Service to write to different s3 buckets, depending on either the environment of the app or the environment specified within the environment field on the component.
If Self Service is deployed to staging then it will write to a staging s3 bucket.
If Self Service is deployed to production it will write to either an integration or production S3 bucket, depending on which is specified within the environment field of the component in question

Judg1lll: support writing to multiple buckets

---

lib/tasks/acceptance_tests.rake

- removing the explicit reference to the s3 environment constant
should fix this
- we may want to think of a better name for the ENVIRONMENT module
that houses these constants as it could lead to developer to think
the constants could be used for RAIL_ENV values.

bau: to fix pipeline errors on environment

---

config/integration_storage.yml
config/secrets.yml

Until the Integration bucket is created do not use the integration storage configuration.

Temporarily hard code the integration bucket name 

---

db/migrate/20190812105927_add_environment_to_sp_components.rb
db/migrate/20190812110003_add_environment_to_msa_components.rb
db/migrate/20190813161922_drop_users_table.rb

We need the environment column to have a default value or the migrations
will fail. Changing the previous migration files is awkward but should
not be a problem for local machines that have already run them as they
will be skipped.
The Self Service app has yet to apply these migrations so should run
them as intended.

Adjust previous migrations

---

Gemfile
Gemfile.lock
config/application.rb
config/initializers/sentry.rb

### What
Add the Raven gem for sending errors to Sentry. The `SENTRY_DSN` envar was set in [this PR](https://github.com/alphagov/verify-infrastructure/pull/270). Sentry will automatically look for this on startup.
Also added some sensitive parameter filtering to Rails config just in case it. Sentry will not send these parameters should it come across them.
https://trello.com/c/lKcAMBvI/528-plug-the-app-to-sentry

Add raven sentry for logging

---

config/initializers/logging.rb
config/initializers/sentry.rb
lib/support/raven/logger.rb
spec/lib/support/raven/logger_spec.rb

We need to extend the Rails logger in order for it to send error log events to Sentry. The default for Sentry is to only send exceptions.
https://trello.com/c/lKcAMBvI/528-plug-the-app-to-sentry

Make Sentry log errors correctly

---

app/controllers/users_controller.rb
app/models/invite_user_form.rb
app/models/user_added_to_team_event.rb
app/views/teams/index.html.erb
app/views/users/index.erb
app/views/users/invite.erb
config/locales/en.yml
config/routes.rb
spec/controllers/users_controller_spec.rb
spec/models/user_add_to_team_event_spec.rb

Display the list of teams on the User Management page. Each should have a button/link to the Invite page.
In preparation for inviting users to teams we need to be able to see the teams and invite new users into them.
Might have also fixed the invite code to invite users to a team.  Handle non-existant gds team as well.

4CnGaY9p List teams on the user management page

---

.pre-commit-config.yaml
pre-commit.sh

It hides the test progress and doesn't show which tests failed.

Revert the pre-commit changes

---

app/models/new_msa_component_event.rb
app/models/new_sp_component_event.rb
config/initializers/constants/environment.rb
spec/factories/components.rb
spec/factories/events.rb
spec/factories/users.rb
spec/models/new_msa_component_event_spec.rb
spec/models/new_sp_component_event_spec.rb
spec/models/publish_services_event_metadata_spec.rb
spec/models/shared_examples/component_event.rb
spec/models/upload_certificate_event_spec.rb

This could be a little contentious. 
In response to [this comment](https://github.com/alphagov/verify-self-service/pull/125#discussion_r316805353) this PR removes all the environment constants. The idea behind this is that they should already be defined in the `hub_environments`.
This prompted a little refactor in order to make use of Factory Bot a little more. The upload_certificate_event still needs to be a factory at some point. Perhaps another PR . . . .

Remove environment constants

---

.pre-commit-config.yaml

The linter on pre-commit hook ran on all files insted of only the app and lib folders.

BAU: Fix the pre-commit linter

---

app/views/layouts/application.html.erb
config/initializers/assets.rb

Favicon and other image assets are not working once deployed.
This is due to them not being in the asset pipeline. This adds the images and
updates the path. The paths can't start with `/` if we want a relative path.

ywk5OlJS: Fix favicon/assets

---

app/assets/stylesheets/_admin.scss
app/assets/stylesheets/application.scss
app/controllers/admin_controller.rb
app/models/user_role_permissions.rb
app/policies/admin_controller_policy.rb
app/views/admin/_certificate.erb
app/views/admin/_msa_component.html.erb
app/views/admin/_service.erb
app/views/admin/_sp_component.html.erb
app/views/admin/_team.erb
app/views/admin/index.html.erb
app/views/layouts/application.html.erb
app/views/sp_components/edit.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/admin_controller_spec.rb

Initial work to help us display what's in the app from a GDS user point of view.
This lists all the components, services, certificates and teams present.
I did not do the localisation, given this is a pure admin view...
(reviewing commit by commit might be easier)

BAU: Add admin interface

---

app/controllers/profile_controller.rb
app/models/new_team_event.rb
app/models/user_role_permissions.rb
config/environments/development.rb
config/environments/production.rb
config/initializers/constants/teams.rb
db/seeds.rb
lib/auth/cognito_stub_client.rb
lib/auth/initial_seeder.rb
spec/lib/auth/initial_seeder_spec.rb

Adding logic to seed Cognito and the DB with minimum required user.
It's not possible to login as a GDS user in a new environment or when
cognito is recreated.
This makes sure there's at least one GDS user and the GDS group.
In addition, updated the `db/seeds.rb` to create the GDS group when
the database is set up.
Open to comments or other suggestions.

96vC6S4J: Seed cognito with a GDS user

---

app/models/healthcheck/checker.rb

It would be a little more helpful if the specific healthcheck name was also logged when something is critical.

Add healthcheck name to logger output

---

lib/storage/storage_registrar.rb

Doesn't use Rails' logger by default

Add logger to storage client

---

app/models/healthcheck/storage_check.rb
lib/storage/storage_registrar.rb

We require the encryption header to be set with all requests that put an object in the config metadata bucket.
https://trello.com/c/PMZorhCM/634-add-permission-for-app-in-staging-to-publish-to-integration-bucket

Fix storage healthcheck

---

app/models/publish_services_metadata_event.rb

We're unable to publish to S3, because we're parsing the list of buckets to
JSON, but querying it by a symbol. This changes it to use the value directly
(rather than symbolizing it first)
Also fix the return value, to return the the component bucket instead of the
Rails.env
Co-Authored-By: Alan Carter <alan.carter@digital.cabinet-office.gov.uk>

BAU: Fix the wrong bucket selection

---

app/models/healthcheck/checker.rb
app/models/healthcheck/storage_check.rb
spec/controllers/healthcheck_controller_spec.rb

More appropriate error and will improve our logging output as well.
Now that we will be connecting to two buckets in production it would be useful to see the bucket name in the logs should an error occur when checking connectivity.
Rails status codes can be found here: http://www.railsstatuscodes.com/

Healthcheck improvements

---

.pre-commit-config.yaml

The regex was too wide capturing the lib folder in the spec folder
which we don't want to lint. This makes sure it only lookes at the root/app and root/lib.

BAU: Fix the linter precommit hook

---

config/environments/development.rb
config/environments/production.rb

We're now using cache to store the JWK. However, we did not configure it
in production. This enables the `memory_store` in a production deployment.
Additionally, enabling the same for dev, so people don't have to manually create
the `caching-dev.txt` file in their tmp folder.

BAU: Fix caching in production (and dev)

---

config/environments/production.rb
lib/auth/jwks_loader.rb

This has been raised to help investigate why the cache appears to be
empty in the live AWS instances of this app.

Added extra debugging and specifics about store

---

lib/auth/cognito_chooser.rb
lib/auth/cognito_stub_client.rb
lib/auth/jwks_loader.rb
lib/auth/jwks_loader_stub.rb

We're using the cache incorrectly, we never refresh it and so once it expires it fails
to validate JWT as it doesn't have the keys. This PR:
- fixes the fetch/call methods to refresh (not only fetch)
- extract the JWKs loader to its own stub method
- loads the stub JWK loader only if cognito_stub is being loaded
- removes the use of global variable for the keys
- removes the need to use caching for local/stub JWKs as there's no reason

BAU: Fix the JWK loader caching issues

---

config/database.yml
test.Dockerfile

After the switch to postgres we need to make sure we can run the tests
in concourse (which is using the test.Dockerfile). It installs
the postgres in Dockerfile, create the vss_test database and
adjust the configuration to not require a password.
[Related pipeline change](https://github.com/alphagov/verify-terraform/pull/1063)

BAU: Add Postgres to the test Dockerfile

---

config/environments/production.rb
config/initializers/devise.rb

- Unmarked cookies will be sent by the web browser as part of a regular HTTP request as well as with the more secure HTTPS request.
- If a logged in user clicks on a link which indicates HTTP as the protocol, rather than HTTPS, then the session cookie will be sent over the network in clear text.
- This config change will prevent ^ from happening.
- Will also force all access to the app over SSL.

Set secure cookies

---

lib/support/raven/logger.rb
spec/support/raven/logger_spec.rb

The default Sentry configuration is set to ignore the following:
```
AbstractController::ActionNotFound
ActionController::InvalidAuthenticityToken
ActionController::RoutingError
ActionController::UnknownAction
ActiveRecord::RecordNotFound
CGI::Session::CookieStore::TamperedWithCookie
Mongoid::Errors::DocumentNotFound
Sinatra::NotFound
ActiveJob::DeserializationError
```
However ActionController::RoutingErrors are still being sent to Sentry. This is possibly to do with the way we extend the default Rails logger with the RavenWriter.
This PR manually adds some handling for the routing specific errors. It is still potentially possible for Sentry to receive debug exceptions from the middleware. We will see how noisy this becomes.
https://trello.com/c/rJCRLBNa/646-filter-out-404s-from-sentry

Do not send routing errors to Sentry

---

app/assets/stylesheets/_components.scss
app/assets/stylesheets/_user_journey.scss
app/assets/stylesheets/application.scss
app/helpers/user_journey_helper.rb
app/views/shared/_user_component_certificates.html.erb
app/views/user_journey/confirmation.html.erb
app/views/user_journey/view_certificate.html.erb
config/locales/en.yml
spec/factories/components.rb
spec/support/helpers/session_helpers.rb
spec/system/visit_index_page_spec.rb
spec/system/visit_user_journey_view_certificate_page_spec.rb

Added summary boxes when there are two signing certificates already uploaded as per the prototype
Doesnt allow user to progress the journey if two signing certificates exist
Created tests to show that the button no longer exists to be able to upload more signing certificates if two already exist
They also test to see if the primary and secondary information is being shown
Created a method which returns true for primary or secondary signing certs
Localise all new static text

Mdakxfzx allow only two signing certificate

---

app/views/layouts/application.html.erb
config/environments/production.rb

- 'Sign' inline javascripts with an unguessable random value (a nonce)
- Use the nonce to whitelist the scripts
- This increases protection against XSS

Remove 'unsafe-inline' from script-src in csp header

---

config/environments/production.rb

Our healthcheck has been consistently failing due to 301 Permanent Redirect.
It seems to be caused by the change we introduced to force SSL.
This disables the redirect (301) on the healthcheck endpoint.

BAU: Fix the failing healthcheck

---

app/controllers/users_controller.rb
app/models/invite_user_form.rb
app/views/users/invite.erb
config/locales/en.yml
spec/models/invite_user_form_spec.rb

- Removed the option to select a GDS role on a non-GDS team
- Added a textual warning when inviting a GDS user (with all permissions)
- Added validation to allow GDS roles to be assigned only to people with a GDS email address
- Removed some redundant code
**Before regardless of a team the user is being invited to:**
**After when inviting to a non-GDS team:**
**After when inviting to a GDS team:**

ml6syFrY: Remove the GDS role option from the invite to a non-GDS team

---

app/helpers/user_journey_helper.rb
app/views/shared/_certificate_details.html.erb
app/views/shared/_component_certificate_doc_links.html.erb
app/views/shared/_user_component_certificates.html.erb
app/views/user_journey/before_you_start.html.erb
app/views/user_journey/confirmation.html.erb
app/views/user_journey/view_certificate.html.erb
config/locales/en.yml
spec/factories/certificate.rb
spec/system/visit_index_page_spec.rb
spec/system/visit_user_journey_before_you_start_page_spec.rb
spec/system/visit_user_journey_check_your_certificate_page_spec.rb
spec/system/visit_user_journey_confirmation_page_spec.rb
spec/system/visit_user_journey_upload_certificate_page_spec.rb
spec/system/visit_user_journey_view_certificate_page_spec.rb

The user journey currently only changes context for the MSA and VSP. It is missing the service provider. For now i will add the option SP.
Also create tests to show the separate SP and VSP journeys
Doing this will help in the follow up stories to implement the updated content on the prototype

XGWgKqpg: Show the clear distinction between the 3 different component types

---

app/controllers/user_journey_controller.rb
app/models/certificate.rb
app/models/certificate_extractor.rb
app/models/certificate_validator.rb
app/models/concerns/certificate_concern.rb
app/models/x509_validator.rb
app/views/user_journey/upload_certificate.html.erb
config/locales/en.yml
spec/controllers/user_journey_controller_spec.rb
spec/models/certificate_extractor_spec.rb
spec/support/helpers/temp_file_helpers.rb

We need to be able to use this in a couple of different places and not always directly linked to an event model.
While the ActionDispatch is used when actually interacting with the controllers it seems the Rack::Test::UploadedFile is the one which is generally used during testing.
Also move the upload_file creation out to a helper module as we will be using it for controller tests as well.
We need to be able to validate certificates separate from the event models. As the user moves between pages in the user journey we need to be able to validate the certificate twice; once when they upload/paste a certificate, and then again after they have viewed it and submitted it.
We do not want to trigger validation on the Certificate model itself as this would mean that validation would occur up to …

Validate the certificates in the user journey flow

---

app/controllers/sessions_controller.rb
app/models/sign_in_form.rb
spec/models/sign_in_form.rb

Currently it's possible to submit the login form empty and it hits Cognito. We should do the validation earlier and don't rely on Cognito and be hitting Cognito unnecessarily.

Added validation to the signin form using a model

---

app/controllers/users_controller.rb
app/views/users/invite.erb

For GDS invites, the roles selector is disabled and thus not sending the value
as part of the request which then fails validation. This change makes sure the value is getting passed and also when a validation fails it shows the right options.

Fix the issue when inviting GDS users

---

app/views/users/index.erb
config/locales/en.yml

Uppercasing the `gds` name to GDS and adding a badge
to highlight it's an admin team.
**Before:**
**After:**

Update how GDS team is displayed

---

app/models/team_member.rb
app/views/profile/show.html.erb
app/views/users/index.erb
app/views/users/show.erb

On the list of users we should not show the different permissions for
GDS users, as they have all of them.
Also capitalized the name of the team when GDS.
**Before:**
**After:**

Update how GDS users are displayed

---

app/controllers/application_controller.rb
app/policies/group_policy.rb
spec/controllers/user_journey_controller_spec.rb
spec/support/auth_support.rb
spec/system/visit_user_journey_before_you_start_page_spec.rb
spec/system/visit_user_journey_check_your_certificate_page_spec.rb
spec/system/visit_user_journey_confirmation_page_spec.rb
spec/system/visit_user_journey_upload_certificate_page_spec.rb
spec/system/visit_user_journey_view_certificate_page_spec.rb

* Add a check which enforces that when dealing with a component, the logged in user must have the same team as that component.
* This prevents accessing other teams' components via URL editing.
* Lots of tests needed to be updated to accommodate this restriction.

p6d47NhK: Enforce component restrictions

---

app/controllers/application_controller.rb
spec/controllers/user_journey_controller_spec.rb

* Added a test which reproduced the vulnerability before it was fixed.
* Also moved the component restriction tests to their own context.

p6d47NhK: Prevent Nil a reference vulnerability

---

test.Dockerfile

The test.Docker file broke when we upgraded the ruby
version as the underlying Linux distro was also upgraded
to Debian busster.

Fix for broken test.Dockerfile

---

.rubocop.yml
app/controllers/certificates_controller.rb
app/controllers/healthcheck_controller.rb
app/controllers/msa_components_controller.rb
app/controllers/password_controller.rb
app/controllers/profile_controller.rb
app/controllers/sp_components_controller.rb
app/controllers/user_journey_controller.rb
app/controllers/users_controller.rb
app/models/component.rb
app/models/healthcheck/storage_check.rb
app/models/new_msa_component_event.rb
app/models/new_service_event.rb
app/models/new_sp_component_event.rb
app/models/new_team_event.rb
app/models/publish_services_metadata_event.rb
app/models/remote_authenticatable.rb
app/models/trigger_metadata_event_callback.rb
app/models/upload_certificate_event.rb
lib/auth/authentication_backend.rb
lib/auth/cognito_chooser.rb
lib/auth/cognito_stub_client.rb
lib/auth/initial_seeder.rb
lib/storage/storage_registrar.rb

We have kept the other changed rule which is about trailing commas
after the last element in hashes and arrays.  Have run govuk-lint-ruby
over lib and app with autocorrect enabled to fix this issue in
our repo.

Updated ruborules to ignore string literals

---

app/controllers/sessions_controller.rb
app/policies/sessions_controller_policy.rb
app/views/devise/sessions/new.html.erb
config/locales/en.yml
config/routes.rb
spec/system/visit_sign_in_spec.rb

Currently, when user enters their password correctly, their session gets populated
and can only finish or fail the journey, no option to cancel.
Even if they visit the homepage again, the session still remembers their details so will be offering them
the TOTP prompt (or whatever step in the journey they were). The user needs to either fail
or delete their cookies in order to get out of the flow.
This adds a cancel button to all the sign-in/up flow screens to reset their session.
Also, added test and localized the strings in there.

BAU: Allow users to leave the sign-in/up flow

---

app/assets/stylesheets/_user_journey.scss
app/views/shared/_user_certificate_view.html.erb

So it is more readable.
**Before:**
**After:**

BAU: Wrap the full certificate in a preformatted tag

---

lib/auth/authentication_backend.rb

In order for users to reset their own password, the email address needs to be verified.
This makes sure the attribute is set when creating the user.

BAU: Set the email_verified attribute when creating users

---

config/initializers/remote_authenticatable.rb
config/locales/devise.en.yml
lib/auth/authentication_backend.rb
spec/system/visit_sign_in_spec.rb

When the user is trying to login with an expired password we should
advise them accordingly.
Also changed the invalid password exception logging level from error to warning, as we don't
need to be alerted on that.

BAU: Display a helpful message when user's temporary password expired

---

app/controllers/user_journey_controller.rb
app/models/certificate_extractor.rb
app/views/shared/_upload_errors.html.erb
app/views/user_journey/upload_certificate.html.erb
spec/controllers/user_journey_controller_spec.rb

Previously we were using the Rails built in flash messages to show the users any errors in validation when they were uploading a certificate.
We now use the correct GOV.UK styling to represent the errors better. We also show the user which part of the form error'd.
https://trello.com/c/r7C6c9PC/587-fix-all-form-validation

Use correct error styles in user journey form

---

config/environments/development.rb
config/environments/production.rb
config/puma.rb
lib/auth/authentication_backend.rb
lib/data/integrity_checker.rb
spec/lib/data/integrity_checker_spec.rb

A fail-safe mechanism to make sure groups in Cognito align with teams in the app.
It could happen that a Cognito group exists without a corresponding team, meaning we
are unable to manage or see it.
On the startup it will compare the cognito groups with teams and create any missing teams.
Also, I have set the puma workers number to one, since traffic is not expected to be high and also it
would cause the checker to run twice, potentially creating race conditions.

Add an integrity checker

---

config/environments/production.rb

Since we might not always want to run it, especially during DB migrations.

Add a feature flag to the integrity checker

---

app/controllers/password_controller.rb
app/views/devise/sessions/new.html.erb
app/views/password/_password_recovery_form.erb
config/locales/en.yml
spec/controllers/password_controller_spec.rb
spec/system/visit_pasword_reset_page_spec.rb

- Fixed the content, which was referring to password changes instead of password reset
- Removed unnecessary double quotes
- Fixed the styling for the 'Forgotten password' link to use govuk styles and size
- Added system test to test rendering and flow
- Changed the behaviour so users are able to refresh the page without the need to request a new code

More adjustments for password reset

---

app/controllers/users_controller.rb
app/policies/member_policy.rb
app/policies/users_controller_policy.rb
app/views/users/show.erb
config/locales/en.yml
config/routes.rb
lib/auth/authentication_backend.rb
spec/controllers/users_controller_spec.rb

Currently, the temporary password expires after 1 day when an user is created/invited.
This adds the functionality to resend a new password/invite for the user if they did not manage
to login and set their own password before the temporary one expired.

ttb2P0KA: Enable admins to resent invitation for users

---

config/locales/devise.en.yml
spec/system/sign_out_spec.rb
spec/system/visit_sign_in_spec.rb

We don't need to display the "Signed in successfully." message to users if
they just logged in.

BAU: Remove the successful sign-in message

---

db/migrate/20190831100615_init_schema.rb

This fixes an error that was occurring when running migrations.

BAU: Use specific rails version for Migration class

---

.gitignore
.pre-commit-config.yaml
.rubocop.yml
Gemfile
Gemfile.lock
README.md
config/environments/test.rb
pre-commit.sh

- replaced `sass-rails` with `sassc-rails`
- the govuk-lint gem has a transient dependency on the unsupported `sass` gem
so I've removed the linter completely and instead use the rubocop directly
while still importing the linter rules from govuk-lint repo

A9cbkuHm: Remove the dependency on to ruby-sass gem

---

config/application.rb
config/environments/test.rb

The CSS compressor needs to be switched off in all the environments. This means
the deployed assets are not compressed/minifed.
This hopefully is a short-term solution until libsass gets an update - tracked https://github.com/sass/libsass/issues/2701 because govuk-frontend is not compatible with libsass (https://github.com/alphagov/govuk-frontend/issues/1350)

BAU: Fix the assets issues

---

app/controllers/teams_controller.rb
app/models/delete_team_event.rb
app/policies/teams_controller_policy.rb
app/views/admin/_team.erb
app/views/teams/index.html.erb
config/environments/development.rb
config/locales/en.yml
config/routes.rb
lib/auth/authentication_backend.rb
spec/controllers/teams_controller_spec.rb
spec/factories/events.rb
spec/models/delete_team_event_spec.rb

- added a new event DeleteTeamEvent to delete existing teams
- prevent deletion when team still has members
- revert if Cognito group cannot be deleted
- deletes team even if the corresponding cognito group doesn't exist

Q2W1VFPI: Enable deleting teams

---

app/controllers/teams_controller.rb
app/models/team.rb
spec/factories/teams.rb
spec/models/new_team_event_spec.rb
spec/models/upload_certificate_event_spec.rb

and that's bad!
- `team_alias` is the team name without spaces (as cognito does not support group names with spaces)
- we were only validating on team name, so `team one` would create a group in with name of `teamone`
and `teamone` name would link to it too since the alias would ended up the same
- made sure we validate the `team_alias` in addition to the team name
Also fixed our code calling cognito twice
- When create the NewTeamEvent it creates a team and a group in cognito (as part of validation).
However, we call `NewTeamEvent.valid?` later in the code which runs the
validators again, (which means calling cognito again).

Fix: Multiple teams can be linked to a single cognito group 

---

app/helpers/user_journey_helper.rb
app/models/certificate.rb
app/views/shared/_user_component_certificates.html.erb
app/views/user_journey/view_certificate.html.erb
spec/system/visit_index_page_spec.rb

Until now the status was driven by the number of enabled signing certs on the component.
This PR adds the real logic with a 10 minute period for which it will
display the deploying status and all the corresponding messages on
primary/secondary certs. I also reshuffled the logic slightly to be more readable.
In the follow-up PR I'll do the encryption cert logic and the TODO bit.

hNmxRDdx: Correct the DEPLOYING status on signing certs

---

app/views/user_journey/view_certificate.html.erb
config/locales/en.yml
spec/system/visit_user_journey_view_certificate_page_spec.rb

If an encryption certificate is being deployed, show the deploying status and
the information message while hiding the button to replace.

hNmxRDdx: Display the deploying message for encryption certs

---

app/controllers/user_journey_controller.rb
app/models/toggle_enable_event.rb
app/policies/group_policy.rb
app/policies/user_journey_controller_policy.rb
app/views/user_journey/view_certificate.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/user_journey_controller_spec.rb
spec/models/disable_signing_certificate_event_spec.rb
spec/models/enable_signing_certificate_event_spec.rb
spec/system/shared_examples/show_component_page.rb
spec/system/visit_user_journey_view_certificate_page_spec.rb

Currently users are not able to disable ("Stop using") the secondary/old certs.
This is to implement the logic to allow them to disable the old one when dual running.
I've also updated the validation on the change event to prevent disable a cert
if it's the only one and the component would end up without certs.
Secondary certificate:
Primary certificate:

1NDRKTxw: Support for disabling certs

---

app/controllers/sp_components_controller.rb
app/models/change_component_event.rb
app/views/sp_components/edit.html.erb
spec/models/shared_examples/change_component_event.rb

- fixed data_attributes to use the actual changed hash (which is required if we want to replay events as part of event sourcing)
- changed the logic to find the changed attributes - it didn't work with multiple changes
- switched using VSP for ComponentType, as that's not a thing which changes - the model should always be SpComponent, only `vsp` attribute value should change
- added a validation for the vsp option
- added a default for validation, just in case we update the model and forget to update the validation
- moved some methods to be private
- updated tests to make sure the above is happening

I2820FMF: Some follow-up fixes for the ChangeComponentEvent

---

app/controllers/profile_controller.rb
app/controllers/sessions_controller.rb
app/helpers/mfa_qr_helper.rb
app/models/mfa_enrolment_form.rb
app/policies/profile_controller_policy.rb
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/profile/show.html.erb
app/views/profile/show_change_mfa.html.erb
app/views/profile/warn_mfa.html.erb
app/views/shared/_mfa_enrolment.erb
config/application.rb
config/environments/production.rb
config/locales/en.yml
config/routes.rb
lib/auth/authentication_backend.rb
lib/auth/cognito_stub_client.rb
spec/controllers/profile_controller_spec.rb
spec/models/mfa_enrolment_form_spec.rb
spec/system/sign_out_spec.rb
spec/system/visit_mfa_preferences_spec.rb
spec/system/visit_profile_page_spec.rb

Users probably need a way to reset their own TOTP device if they for example upgrade their phone or move to a new TOTP app. This is important as if a user losses their TOTP device then there is no way for an admin to reset this on their behalf.

I7IBiAot Allow users to change their own MFA settings

---

app/models/delete_team_event.rb
app/views/admin/_team.erb
config/locales/en.yml
spec/models/delete_team_event_spec.rb

GDS team/group is an admin team and should never be deleted.

BAU: Prevent deleting GDS team

---

app/views/users/show.html.erb

On the user details screen, we display links to password reset and MFA reset. They're not used and will not be at this stage.

1YBAF1GT: remove unused password and mfa reset links

---

app/models/x509_validator.rb
config/locales/en.yml
spec/models/upload_certificate_event_spec.rb
spec/support/certificate_support.rb
spec/support/pki.rb

Enforcing higher security standards by only accepting certificates with 'SHA256withRSA' algorithm. When we do checks/validation on a new certificate, we should also validate the algorithm used to sign the cert.
The 'SHA256withRSA' signature algorithm is currently deemed as sufficiently secure and we therefore we should not accept other (less secure) algorithms to maintain Verify integrity and security.
Trello Ticket: https://trello.com/c/3t1kxCb9

3t1kxCb9 Reject certificates with the wrong algorithm

---

app/views/layouts/application.html.erb

Previously, when the window width was small(such as when using a mobile) the menu icon was not clickable and the menu did not expand. 
It now does. 
This issue arose because the CSS class names were not updated when we upgraded the design system.

CbTC5TPe: Fixed menu not opening on mobile display

---

app/models/component.rb
lib/auth/cognito_stub_client.rb
spec/models/component_spec.rb

The change to cognito_stub_client was to satisfy rubocop
See Trello: https://trello.com/c/jhmC5xc1

Removes expired certs before producing meta-data

---

app/models/certificate.rb
app/models/component.rb

It is nice to have an expired? member on the Certificate model
so it can be reusable. i.e see Component

BAU: Added expired? member to Certificate model

---

app/controllers/services_controller.rb
app/controllers/sp_components_controller.rb
app/models/assign_sp_component_to_service_event.rb
app/policies/component_policy.rb
app/views/admin/_service.erb
app/views/msa_components/show.html.erb
app/views/services/new.html.erb
app/views/sp_components/show.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/sp_components_controller_spec.rb
spec/factories/events.rb
spec/models/assign_sp_component_to_service_spec.rb
spec/models/service_spec.rb
spec/system/visit_msa_service_new_spec.rb
spec/system/visit_service_new_spec.rb
spec/system/visit_sp_service_new_spec.rb

This PR adds the ability to create services independently of components, via the Services tab of the admin page.
It is also now possible to associate an SP component with a service.  Admin users can select a service from a drop-down when viewing the SP component, and click a button to associate that service with the component.  Only services which do not already have an SP component associated with them will be listed.
This functionality is needed for MSA components too; that will follow in a later PR.

Eq8a6mon: Enable adding services to multiple components (part 1: SP components)

---

app/controllers/services_controller.rb
config/locales/en.yml
spec/controllers/services_controller_spec.rb

When deleting a service we are checking for the existence a service
no feedback is when the service is not found.

BAU: flash message when deleting service not found

---

app/models/healthcheck/storage_check.rb
app/models/publish_services_metadata_event.rb

By default, when a file is written to a S3 bucket from a different account, the
destination account does not have access to the file/object.
This makes sure the bucket owner has access to the object itself.
https://aws.amazon.com/premiumsupport/knowledge-center/s3-bucket-owner-access/

BAU: Fix S3 AccessDenied when cross-account

---

app/controllers/msa_components_controller.rb
app/models/assign_msa_component_to_service_event.rb
app/models/service.rb
app/models/trigger_metadata_event_callback.rb
app/views/msa_components/show.html.erb
config/routes.rb
spec/controllers/msa_components_controller_spec.rb
spec/factories/events.rb
spec/models/assign_msa_component_to_service_spec.rb

This is the equivalent to earlier PR 261 but for MSA components, and with equivalent changes from PR 270 also included.
https://trello.com/c/eq8a6mon/688-enable-adding-a-service-to-multiple-components

eq8a6mon - Enable adding services to multiple components (part 2: MSA components)

---

app/controllers/admin_controller.rb
app/policies/admin_controller_policy.rb
app/views/admin/_publish.erb
app/views/admin/index.html.erb
config/routes.rb
spec/controllers/admin_controller_spec.rb

As admins we should be able to publish latest metadata manually - in case of previous
failures or any other reasons.

BAU: Add the ability to trigger metadata publish manually

---

app/views/layouts/main_layout.html.erb
spec/system/visit_index_page_spec.rb

Users who don't have user manager role, should not see that option on dashboard.

BAU: Don't show the Team Members link to the user without permissions

---

app/views/shared/_user_certificate_view.html.erb
app/views/shared/_user_component_certificates.html.erb
config/locales/en.yml
spec/system/visit_index_page_spec.rb
spec/system/visit_user_journey_view_certificate_page_spec.rb

Previously the services used by a component were not shown on the dashboard
They now are.

Services used by component now show & associated test

---

app/views/sp_components/show.html.erb

The accordion was missing the updated 'govuk' tag. You can now view previous encryption certificates and all certificates

FIX: accordion in admin view for components certificates

---

app/views/layouts/main_layout.html.erb

Previous change forgot about GDS users, i.e. it was hidden for GDS roles.
Using policy should be more realiable and consistent.

REFACTOR: Don't display Team management to users without permissions

---

app/models/component.rb
app/models/publish_services_metadata_event.rb
spec/models/component_spec.rb

We're currently publishing metadata for all the components regardless of
their environment. Meaning we publish the same JSON file to different buckets.
The correct behaviour should be that only the components for that environment are present
and published in the metadata.

BUGFIX: Publish metadata for specific environments

---

app/views/user_journey/view_certificate.html.erb

There was insufficient isolation between the encryption and signing, and primary and secondary certs.
Causing some of the text and buttons to display incorrectly.
Co-Authored-By: Amrit Sidhu <amrit.sidhu@digital.cabinet-office.gov.uk>

BUGFIX: Inconsistencies in the view and buttons when deploying

---

app/views/shared/_user_component_certificates.html.erb

Given the larger complexity of the other ticket which combines grouping and sorting.
For private beta we only need the grouping, since none of the certs will be expiring.
The diff is confusing, but all I did was added the `group_by` method first and move the logic one level down.

BAU: Group by environment

---

app/views/user_journey/index.html.erb
spec/system/visit_index_page_spec.rb

We were still grouping components by type. This changes uses one list of components,
instead of splitting them to MSA and SPs, which was creating
duplicate environment groupings for each type.

BUGFIX: Fix grouping

---

app/views/user_journey/check_your_certificate.html.erb
config/locales/en.yml
spec/system/visit_user_journey_check_your_certificate_page_spec.rb

The current content is relevant to encryption certs, not signing. Adding a new content for signing.
**Before:**
**After:**

BAU: Correct the content for signing cert on confirmation page

---

app/views/user_journey/confirmation.html.erb
config/locales/en.yml
spec/system/visit_user_journey_confirmation_page_spec.rb

The instructions said to delete signing key, but it actually is to replace.
From `Once you've received the email, delete the old %{usage} key and certificate from your %{component} configuration.`
to `Once you've received the email, replace the old %{usage} key with the new one in your %{component} configuration.`

BAU: Fix content inaccuracy on confirmation page for signing SP

---

app/views/layouts/application.html.erb

On mobile devices, the website doesn't scale properly. It's shown in a full-desktop view. We're using responsive components so we should take the advantage of it.
Added missing meta tag from the page template on the design system

X7Gs9ssq: Fix the website responsiveness

---

app/controllers/password_controller.rb
app/views/password/password_form.html.erb
config/locales/en.yml

After speaking with Chris I removed the hint text on the change password isn't necessary.
The page is also now using the wrong layout

1XQnvb8P: Fix the change password layout and remove hint text

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/views/layouts/application.html.erb
app/views/shared/_error_summary.html.erb
app/views/shared/_upload_errors.html.erb

Turbolinks don't work super well. Especially in our admin area and the scrolling
is not ideal when navigating between pages and it doesn't scroll to the top of the page.
I think it's better to disable now. Open to comments though!

BAU: Disable turbolinks

---

spec/acceptance/user_journey_spec.rb

- Changes have been made which break the current end to end tests.
- These changes are that a user cannot rotate the a which is being deployed.
- If the acceptance tests run quickly in sequence, the second test would fail as the cert is still deploying.
- This commit updates the spec to only upload a certificate which is not currently deploying.
- More components + msa encryption certs have been added to the acceptance test staging account for cases where there are multiple deployments in quick succession (aka lots of acceptance tests are run and we need to take into account the real-time deployment time).

Jo4SzZ0J: Update end to end tests

---

lib/support/raven/logger.rb

We're meant to be excluding 404 errors in Sentry. However, our current logic does not seem to be working properly.
The reason is that the message might start with empty space (e.g.`  \nActionController::RoutingError (No route matches [GET]`)) and in AWS it's
prepended with the instance ID.

Fix the Sentry 404 exclusion

---

app/views/user_journey/before_you_start.html.erb
app/views/user_journey/confirmation.html.erb
config/locales/en.yml
spec/system/visit_user_journey_before_you_start_page_spec.rb
spec/system/visit_user_journey_confirmation_page_spec.rb

The instructions are not accurate and can be confusing (as highlighted during the
private beta testing).
This PR:
- changes the instructions for MSA signing so
that Before you start advises users to add the new signing key to secondary position.
- changes the next steps on confirmation advising to promote the secondary cert to primary and delete it
There will be corresponding changes in the docs.
**Before on "Before you start"**
**After on "Before you start"**
== == == == ==
**Before on confirmation**
**After on confirmation**

tBLqcTb2: Change the content for MSA signing rotation

---

app/controllers/certificates_controller.rb
spec/controllers/certificates_controller_spec.rb

Currently, when we disable a cert, we get a confusing error message saying
the component has to have at least one certificate.
This is due to the fact, that validation happens during the event creation and
then we call `valid?` again, which now adds the error because
the cert was disabled during the event itself.
This change looks at the errors on the model instead of re-running the validation.

BUGFIX: Do not validate twice on disable/enable event

---

app/controllers/user_journey_controller.rb
app/helpers/user_journey_helper.rb
app/models/certificate.rb
app/models/component.rb
app/views/shared/_user_component_certificates.html.erb
app/views/user_journey/index.html.erb
spec/controllers/user_journey_controller_spec.rb
spec/models/component_spec.rb
spec/support/matchers/appear_before.rb
spec/system/visit_index_page_spec.rb

[**Change the ordering logic on the dashboard**](https://trello.com/c/8ahctkdG/738-change-the-ordering-logic-on-the-dashboard)
On the dashboard, the components should be grouped by environment. Production first, Integration second, within each group/section, any components with an expiring cert should at the top of the group.

8ahctkdg: change the ordering logic on the dashboard

---

entrypoint.sh

We want to pre-compile the assets before we let the app start. Fargate is going to use
this file to start the app.
Corresponding startup change https://github.com/alphagov/verify-infrastructure/pull/329

8Dakh37S: Add entrypoint.sh

---

app/views/user_journey/confirmation.html.erb
config/locales/en.yml

https://trello.com/c/j8OJ2sMr/756-content-change-to-non-dual-running-flow
We've moved this instruction to earlier in the flow, to hopefully minimise any downtime
Before:
After:

j8OJ2sMr: Content change to non-dual running flow

---

app/views/user_journey/confirmation.html.erb
config/locales/en.yml

Beth also requested we remove this heading as its unnecessary.
Also added a full stop at the end of a sentence
Before:
After:

j8OJ2sMr: Remove unnecessary sub heading

---

app/controllers/users_controller.rb
app/models/invite_user_form.rb
app/models/remote_authenticatable.rb
app/models/team_member.rb
app/models/user.rb
app/views/users/invite.html.erb
lib/auth/authentication_backend.rb
spec/controllers/users_controller_spec.rb
spec/factories/users.rb
spec/models/invite_user_form_spec.rb
spec/system/visit_invite_user_spec.rb

- The invite user form should be displaying First / Last name over Given / Family name.
- Due to Cognito reasons we still should be using Family / Given name in the backend.
- Displays validations with updated content.
- Fixing displaying validations for the role checkboxes has also been snuck in...
- Linking from the error summary at the top of the form to the form fields was also previously broken and is now fixed.

Change form fields on invite user form

---

app/controllers/admin_controller.rb
app/policies/admin_controller_policy.rb
config/routes.rb

This is a temporary testing mechanism to figure out what needs to be changed/configured
for allowing traffic between self-service and hub.

OFCDsnoA: Test connection between self-service and hub

---

app/controllers/admin_controller.rb

Our microservices run on HTTPS and setting a timeout helps with debugging.

OFCDsnoA: Add some more options to the test method

---

app/controllers/concerns/controller_concern.rb
app/controllers/user_journey_controller.rb
app/views/user_journey/confirmation.html.erb
app/views/user_journey/publish_failed.html.erb
config/locales/en.yml
spec/system/visit_user_journey_check_your_certificate_page_spec.rb
spec/system/visit_user_journey_confirmation_page_spec.rb

Confirmation page when cert fails to publish to S3:
Confirmation page when cert publishes to S3:

plgVsdxI: Update user journey content if certificate fails to publish

---

app/controllers/admin_controller.rb
app/controllers/healthcheck_controller.rb
app/models/healthcheck/hub_check.rb
app/policies/admin_controller_policy.rb
config/application.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/routes.rb
spec/controllers/healthcheck_controller_spec.rb
spec/system/visit_healthcheck_spec.rb

We've merged required terraform changes to enable traffic between self service
and hub.
Now adding a healthcheck to monitor the connection
Also removed the old test code (the second commit)
To be merged only after: https://github.com/alphagov/verify-infrastructure/pull/332

OFCDsnoA: Add healthcheck for the hub connection

---

Gemfile
Gemfile.lock
lib/notify/notification.rb

Do not merge until: https://github.com/alphagov/verify-infrastructure/pull/333 has been merged.
- You will need to set the `NOTIFY_KEY` in your ENV file
example of sending an email from a controller method:
```
require 'notify/notification'
class TestMailController < ApplicationController
include Notification
def test_email
send_email(email_address: "rosa.fox@digital.cabinet-office.gov.uk")
end
end
```

{do not merge} iJMydfG2g: Initial set up for Notify integration

---

app/models/certificate_in_use_event.rb
app/models/certificate_notification_sent_event.rb
db/migrate/20191122125659_add_hub_use_notification_to_certificate.rb
db/schema.rb
spec/factories/events.rb
spec/models/certificate_in_use_event_spec.rb
spec/models/certificate_notification_sent_spec.rb
spec/models/certificate_spec.rb

Scope: This task is just to add suitable database fields, and events to update their values; other tasks will build on this.
Acceptance criteria:
Certificate objects have an optional date field which indicates when that cert is expected to start being used throughout Hub, and a boolean field which indicates whether an email notification to confirm that the cert is in use has been sent.
When a new certificate object is created, the optional date field should be empty and the boolean flag should be false.
Events exist to update the optional date field and the boolean flag.
Tests exist for the previous two acceptance criteria
Note: Making the fields actually sync up with the real cert status in Hub is NOT in scope for this task.

tv2hoipg record whether cert is being used by hub

---

spec/acceptance/user_journey_spec.rb

We've recently added the webmock gem which by default does not
allow real HTTP connection. We need to allow it for acceptance tests.

BAU: Fix acceptance tests

---

app/controllers/certificates_controller.rb
app/models/toggle_enable_event.rb
app/models/upload_certificate_event.rb
app/models/x509_validator.rb
lib/notify/notification.rb
spec/models/upload_certificate_event_spec.rb

Admins should be able to upload certs which expire at any time. This will enable us to
onboard services which are expiring within less than 30 days.
The rest of the validation remains the same.
Also fixed a linting issue and a small bug (separate commits)

wSQ6uwPR: Allow admins to override cert expiry validation

---

app/views/user_journey/index.html.erb
config/locales/en.yml
spec/system/visit_index_page_spec.rb

When only one cert is expiring it says `1 certificates are expiring soon.` It should say `1 certificate expiring soon.`
Before:
After:

kvCAeS84: Pluralize the expiring notice on the dashboard correctly

---

app/controllers/password_controller.rb
app/controllers/users_controller.rb
app/models/reset_user_password_event.rb
app/policies/member_policy.rb
app/policies/password_controller_policy.rb
app/policies/users_controller_policy.rb
app/views/users/show.html.erb
app/views/users/show_reset_user_password.html.erb
config/initializers/remote_authenticatable.rb
config/locales/en.yml
config/routes.rb
lib/auth/authentication_backend.rb
lib/notify/notification.rb
spec/controllers/session_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/system/visit_sign_in_spec.rb
spec/system/visit_users_reset_user_password_page_spec.rb

Admins now have the functionality to reset users passwords.
When viewing team members there is now a link to reset a users password. That then takes you to a confirmation page where you then can confirm. 
When the user tries to next log in an exception is raised: `PasswordResetRequiredException` redirecting them straight to the views which already exist for the forgot password flow, minus the part which wants the user to enter an email. We already know the email from when the user tries to log in. The verification code email is straight away sent and just requires the user to enter it and create a new password.

Fevlnkrg: enable admins to reset passwords for users

---

app/helpers/application_helper.rb
app/models/certificate.rb
app/views/user_journey/confirmation.html.erb
config/locales/en.yml

Here are the content changes that we need to make following the content 2i: https://docs.google.com/document/d/1y9NDF-XQrqoTsQyStKJN0VuD65eVou-FUmZmtivJTqE/edit# 
In summary, we need to: 
- Change the time convention in all flows to 12 hour, not 24 hour, if possible 
- Remove the link to the documentation on all the 'confirmation' pages
- Simplify some text on all the 'upload cert' pages
- Simplify some text on all the 'check cert' pages
- Clarify a sentence on the ‘check cert page’ for the encryption cert flow, for service providers that do not support dual running

P8ifzwdc: small content changes

---

app/controllers/certificates_controller.rb
app/models/replace_encryption_certificate_event.rb
spec/models/replace_encryption_certificate_event_spec.rb

Previously, we've added the ability for admins to override the certificate validation for
expiry. This also adds it for encryption certificate.
Previous PR: https://github.com/alphagov/verify-self-service/pull/315

BAU: Enable admins to override expiry restrictions on encryption certificates

---

app/views/shared/_user_component_certificates.html.erb

The tags when the cert is expiring and deploying are not delimited by a space meaning
the resulting class is `app-certificate-tag-deployingapp-certificate-tag-expiring`
This scenario should rarely happen, but it should be correct regardless.

BUGFIX: Missing space between classes

---

app/controllers/password_controller.rb
app/controllers/user_journey_controller.rb
app/views/layouts/application.html.erb
app/views/password/_password_recovery_form.erb
app/views/users/show_reset_user_password.html.erb
config/initializers/remote_authenticatable.rb
config/locales/devise.en.yml
config/locales/en.yml
config/routes.rb
spec/controllers/session_controller_spec.rb
spec/system/visit_sign_in_spec.rb

The password controller now uses the column two thirds
Fix form label to just be Email
Remove sign in to continue as its self explanatory
Added a small description to reset user password page:
Added specialised text to reset password flow when admin reset a users password:

EPJNPyyX: Content changes to admin reset password flow

---

app/controllers/user_journey_controller.rb
spec/system/visit_user_journey_check_your_certificate_page_spec.rb

The warning that publishing to S3 failed does not show on encryption certs. Fixed the logic which decides which views are being rendered.
We was only testing the encryption journey unsuccessful publish, created a test for signing

XsLYPuxh: Bug - failed to publish now renders correctly when necessary

---

app/models/polling/cert_status_updater.rb
config/application.rb
spec/factories/certificate.rb
spec/models/polling/cert_status_updater_spec.rb

This module provides code which handles checking Hub for the current status of a particular certificate, and taking appropriate action based on the result.  If the given cert is included in the list of certs returned by Hub, then the in_use_at field on that cert will be set to a timestamp representing the moment by which we expect all Hub cert caches to have expired, and thus can trust that the cert is being used throughout all of Hub.
https://trello.com/c/psV0aeSY/780-update-certs-status-timestamp-based-on-result-from-hub

Create CertStatusUpdater module

---

Gemfile
Gemfile.lock
app/models/polling/scheduler.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
spec/models/polling/scheduler_spec.rb

**HKYMG4ca: generic polling functionality**
Is the first of more PR to come for [Poll Hub to get status of new certs](https://trello.com/c/HKYMG4ca/781-poll-hub-to-get-status-of-new-certs). It add the rufus-scheduler gem and a class to wrap around **rufus-scheduler**. It can be used for
**polling action** or can be used to **schedule an action** to occur at some
later point.
- it accepts a mode
i.e mode('every') for polling
mode('in') for running a later point
-  a perform which requires a lambda
-  until is the condition which must evaluate to true for it.
```
scheduler.mode(:every, '2m')
.perform(->{ 'hello verify self service...' })
.until(scheduler.action_result.present?)
```

Hkymg4ca generic scheduler polling functionality

---

app/models/certificate_expiry_reminder.rb
app/models/component.rb
lib/notify/notification.rb
lib/tasks/check_expiring_certs.rake
spec/models/certificate_expiry_reminder_spec.rb

When a cert is expiring in 30, 7 or 3 days, an email notification is sent
to the team's members.
The module with the logic is going to be triggered daily using the rake task.

o8P0uBic: Send reminder email for expiring certs

---

app/controllers/profile_controller.rb
lib/notify/notification.rb
spec/controllers/profile_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/models/certificate_expiry_reminder_spec.rb
spec/support/notify_support.rb

An email is sent when a user changes their name.
Also, introduced a new helper for Notify to make testing easier.
Review a commit by commit, the second one is just refactoring to use the new helper methods.

aU8jrM6b: Send a notification email when user changes their name 

---

app/models/remote_authenticatable.rb

First name and last name have never been populated from the session correctly!
Always being nil as it was looking at the wrong elements.
This will fix other PRs which rely on first_name:
https://github.com/alphagov/verify-self-service/pull/330
https://github.com/alphagov/verify-self-service/pull/332

BUGFIX: Incorrect serialization of user data

---

app/controllers/profile_controller.rb
lib/notify/notification.rb
spec/controllers/profile_controller_spec.rb

When user chooses to change their MFA, an email is sent.

4Twxnq3H: Send a notification email when user changes their MFA

---

lib/notify/notification.rb

It provides more useful error than `e.to_s`.
Also some linting fixes.

REFACTOR: Use 'e.message' on the Notify client

---

app/models/forgotten_password_form.rb
app/models/password_recovery_form.rb
app/models/sign_in_form.rb
app/models/update_user_email_form.rb
lib/auth/authentication_backend.rb

Currently, the emails used as usernames are case sensitive. This adds a downcase method on
models when we're handling emails.
I did consider putting to the API calls cognito only, but we often store the email
in the session for further processing (MFA enrolment) which would create
discrepencies.
Open to other suggestions.

gbOCPRmz: Make usernames/emails case insensitive

---

config/environments/development.rb
config/environments/test.rb

So that it can accomodate hub urls(hub-config-host) for different environment
and secure headers for integration

9lg6CX1O: changed structure of hub_enviroments

---

spec/models/component_spec.rb
spec/models/new_team_event_spec.rb

removed 'has team event' test because it is redundant and implied in valid and persisted test

bau to remove flaky redundant test

---

spec/system/visit_change_password_spec.rb

This PR https://github.com/alphagov/verify-self-service/pull/323 broke the pipeline 
I've updated the test included in that PR to fix this.

Updated test to account for inclusion of notify

---

app/controllers/msa_components_controller.rb
app/controllers/sp_components_controller.rb
app/models/change_component_event.rb
app/models/concerns/hub_environment_concern.rb
app/models/healthcheck/hub_check.rb
app/models/healthcheck/storage_check.rb
app/models/new_msa_component_event.rb
app/models/new_sp_component_event.rb
app/models/polling/cert_status_updater.rb
app/models/publish_services_metadata_event.rb
app/views/admin/_publish.erb
app/views/shared/_component_environments.erb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
lib/api/hub_config_api.rb
spec/lib/api/hub_config_api_spec.rb
spec/models/polling/cert_status_updater_spec.rb

This PR uses the new structure of hub_environment that has secure-header for integration.
It also removes hub_environment_legacy

9lg6cx1o using secure header and removing hub_environment_legacy

---

app/models/concerns/hub_environment_concern.rb
app/models/healthcheck/storage_check.rb
config/environments/development.rb
config/environments/test.rb

We can't currently deploy as the healthchecks are failing. This is due to a change in data
structure of the hub_environments. This aligns the dev, test and production
format to be the same to avoid this in future.
We were also missing the authentication_header config on test.rb

BAU: Fix failing healthchecks

---

app/models/healthcheck/hub_check.rb
lib/api/hub_config_api.rb

The URI.join method works differently than I assumed. The integration hub URL
is not a root so `URI.join('http://www.test.com/abc/def', '/service-status')`
becomes `http://www.test.com/service-status` which is incorrect. By switching to standard join should resolve it.
Also refactored the hub healthcheck to provide more useful information when it fails. And started using the the `success?` method from Faraday.

BAU: Change the way we build URLs

---

app/views/events/index.html.erb

Currently, in the event log we're displaying just user ID, which makes it
slightly difficult to find out who the actual user is. This PR adds a link to the user's profile
to see their name.

BAU: Link events to users

---

app/controllers/user_journey_controller.rb
app/models/upload_certificate_event.rb
config/locales/en.yml
spec/controllers/user_journey_controller_spec.rb
spec/models/upload_certificate_event_spec.rb
spec/system/user_visits_events_page_spec.rb
spec/system/visit_user_journey_check_your_certificate_page_spec.rb

When the user clicks back in the browser it goes to the form page again where if the user clicks the submit button again, it creates a new record in the database.
Added validation in the controller to stop multiple signing certs being added
Add extra validation on the UploadCertificateEvent itself to reinforce the functionality that a user cannot upload more than two signing certs
Fix broken tests - we are now calling the component on validation so it is required in tests

3pavjdif: BUG duplicate records being submitted

---

app/controllers/users_controller.rb
app/views/password/_password_recovery_form.erb
config/locales/en.yml
lib/notify/notification.rb
spec/controllers/users_controller_spec.rb

Send a notification email when user has their password reset by an admin as per https://docs.google.com/document/d/1CYF-K3hKIdrryaTvc52CZtl80kbwAoJnWYoiFxkL9RU/edit#heading=h.lduypbyjzs1t
An email is sent when an admin resets a users password.
Amend an existing test to show the email functionality working.
Change content on the reset password page
The email that is sent to the user:
The changed content on reset password page:

WtjPds2P: Send a notification email when admin resets a users password

---

app/assets/stylesheets/_components.scss
app/helpers/user_journey_helper.rb
app/models/certificate.rb
app/views/shared/_user_component_certificates.html.erb
spec/system/visit_index_page_spec.rb

When certs were expiring the tags were not correct, as there was a rounding going on
so certs expiring in 11 hours showed as "EXPIRES IN 1 DAYS" and under 11 hours
showed as "EXPIRES IN 0 DAYS".
Similar with expired certs which showed "EXPIRES IN -2 DAYS" if expired 2 days ago.
This PR adds more granular metrics for hours and minutes and pluralize accordingly.
Also extracted the logic for selecting the right class for the label to the helper.
**Before:**
**After:**

mb664GkE+GmBNuF4o: Fix expiring certs labels

---

app/models/certificate_expiry_reminder.rb
app/models/component.rb
spec/models/certificate_expiry_reminder_spec.rb
spec/system/visit_invite_user_spec.rb
spec/system/visit_mfa_preferences_spec.rb
spec/system/visit_profile_update_user_name_spec.rb

The current logic for finding expiring certs is flawed. It works under the assumption
that certs are in use when their 'enabled' attribute is set to true.
It's the case for signing certs. However, encryption certs are behaving differently.
Encryption certs are replaced since there is one-to-one relationship
from a component perspective.
This change adds a new method on the component to check whether a given cert
is active/used by the component. This method is then used to find the certs which
are expiring and teams should be notified about.
I admit this is not the most performant solution, but should not present any
challenges for a long time. The alternative approach would be to start changing the
'enabled' attribute on the encryption certs, which adds quite a lot of complexity.
Also, in …

RK8WfX73: Fix the logic for finding expiring certs 

---

app/models/publish_services_metadata_event.rb
lib/notify/notification.rb
spec/models/publish_services_event_metadata_spec.rb

As part of our protection, we want to be notified of any out-of-hours activity which
could introduce a change to the production environment.
This change adds an additional logic to the production publish event which checks whether
it's out-of-hours (6PM-8AM and weekends) and sends an email if it is.
Email template:

69ughKnj: Out-of-hours notification

---

app/models/component.rb
spec/models/component_spec.rb

This reverts [PR#260](https://github.com/alphagov/verify-self-service/pull/260). It turns out the hub is not able
to handle missing certs and fails with NullPointerException.
This will also make it possible for Grafana to see expired certs in the published metadata file.
Discovered from Sentry logs

BAU: Keep publishing expired certs

---

lib/notify/cert_status_notifications.rb
lib/notify/notification.rb

When a certificate that has been added by a reying party is confirmed to be in use by the Hub, we will send them an email to confirm that the cert is ready.  This commit adds code which chooses which template to use and sends the email, but at present nothing calls it.
Once this PR is merged I will need to look into integrating it with the work Ola has been doing.
https://trello.com/c/OjUWN78Y/782-schedule-an-email-when-cert-is-confirmed-to-be-in-use-by-hub

Email templates for when cert is ready

---

app/views/layouts/main_layout.html.erb

So it's consistent with the Teams view.
**Before:**
**After:**

BAU: Uppercase the GDS team name in the banner

---

app/controllers/user_journey_controller.rb
spec/controllers/user_journey_controller_spec.rb

user journey confirmation logic is a little difficult to follow
this is an attempt to make easier to follow the logic by
- redirecting when more than 2 signing certificates
- render upload errors if there are any?
- render confirmation for published encryption certificate
- render confirmation for published signed certificate
- else render failed publish template

bau: refactor confirmation logic

---

app/models/component.rb
app/models/concerns/hub_environment_concern.rb
app/models/polling/dev_cert_status_updater.rb
app/models/polling/scheduler.rb
app/models/polling/worker.rb
app/models/publish_services_metadata_event.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
lib/api/hub_config_api.rb
spec/models/certificate_expiry_reminder_spec.rb
spec/models/component_spec.rb
spec/models/polling/scheduler_spec.rb
spec/models/publish_services_event_metadata_spec.rb
spec/models/upload_certificate_event_spec.rb
spec/support/notify_support.rb
spec/support/stub_hub_config_api_support.rb

**[(part of [EPIC] Implement a way for self-service to know when the hub is using the new certificates](https://trello.com/c/HAgIQnnZ/773-epic-implement-a-way-for-self-service-to-know-when-the-hub-is-using-the-new-certificates)**
**Background:** In order to send out email notifications to the cert owner when a new cert is confirmed to be in use by Hub, the app will need to poll the Hub until it is confirmed that the cert is being used. Other cards ([Poll Hub to get status of new certs ](https://trello.com/c/HKYMG4ca/781-poll-hub-to-get-status-of-new-certs) and [Update cert's status timestamp based on result from Hub](https://trello.com/c/psV0aeSY/780-update-certs-status-timestamp-based-on-result-from-hub)) cover implementing the details of performing that polling, but we also need to …

9lg6cx1o initiate polling when a cert is added

---

config/environments/production.rb

- Acceptance test fails because the Scheduler hasn't been initialized
- in production.rb

bau-fix-unitialized-scheduler

---

app/views/admin/_certificate.erb

So we can see values in the in_use_at field of a certificate. This shows that when polled the hub has return the certificate and the in use at field has been populated

bau add in use at field to certificate admin page

---

app/models/certificate.rb
app/models/polling/dev_cert_status_updater.rb
config/locales/en.yml
spec/models/publish_services_event_metadata_spec.rb
spec/support/time_helpers.rb
spec/system/visit_index_page_spec.rb
spec/system/visit_user_journey_view_certificate_page_spec.rb

https://govukverify.atlassian.net/browse/HUB-416
Currently when deploying a certificate in the Self service application, the deploying status of the certificate is based on update_at field. New  or replaced certificates are shown as deploying for 10 minutes after which it is assumed that the are in use by the Hub. However, this logic should be based on the outcome of polling the hub, which updates the in_use_at field for the the certificate.
**Acceptance Criteria**
-   deploying status a certificate is driven  by the in_use_at field
-   All references to a 10 minutes deployment wait are removed
-   All specs depending on the deploying status pass

Hub-416: change implementation certificate deploy status

---

app/views/shared/_user_component_certificates.html.erb
config/locales/en.yml

The heading of the table was referring to `user_journey.certificate` however,
it's defined twice, once as a value and second time as a group including sub-keys.
The page was rendering the sub-keys. It wasn't visible to the user because of
being it visually hidden for screen readers.
This PR changes the certificate key to certificate_heading to remove the duplication.
**(This is a very old commit forgot to raise a PR for)**

BAU: Fix the incorrect reference

---

spec/acceptance/user_journey_spec.rb

- This is to allow self service acceptance test to use the component
entity id specified in [Verify Hub federation configuration](https://github.com/alphagov/verify-hub-federation-config/pull/482)

bau-modify-self-service-acceptance-test

---

config/locales/en.yml

We've published the latest docs so we no longer should be pointing users
to the prototype docs.

BAU: Change the URLs of the docs

---

app/models/certificate_expiry_reminder.rb
app/models/certificate_in_use_event.rb
lib/auth/authentication_backend.rb
lib/notify/cert_status_notifications.rb
lib/notify/notification.rb
spec/models/certificate_in_use_event_spec.rb
spec/models/component_spec.rb
spec/support/notify_support.rb
spec/system/user_visits_events_page_spec.rb
spec/system/visit_index_page_spec.rb

**What?**
When Self Service polls the hub successful and a result is acquired. The app needs to inform the service by emailing members of the team that their certificate has been deployed successfully.
**Why?**
This would inform all service team members and provide a link into the app where they can view the certificate and continue with other activities associated with managing their certificates.
**How?**
Immediately after the in_use_at field has been updated an email would be sent to each team member.
- An email is sent to each member of the service team when the in_use_at field is updated
- The appropriate email template is used in to sending the email notification

Hub-419 schedule email when certificate is being used by hub

---

app/models/msa_component.rb
app/models/sp_component.rb
spec/models/assign_msa_component_to_service_spec.rb
spec/models/assign_sp_component_to_service_spec.rb

Related to https://govuk.zendesk.com/agent/tickets/3912824
This is to ensure that when a component that has an association to a service is deleted.
The association i.e the component reference in the service is removed.
This would allow re-associating a new component to the existing service.

ZD-3912824 De-associate deleted component reference

---

app/models/certificate_expiry_reminder.rb
app/models/certificate_in_use_event.rb
app/models/component.rb
app/models/polling/cert_status_updater.rb
app/models/polling/scheduler.rb
config/environments/test.rb
lib/auth/authentication_backend.rb
lib/notify/cert_status_notifications.rb
lib/notify/notification.rb
spec/models/certificate_in_use_event_spec.rb
spec/models/component_spec.rb
spec/models/polling/scheduler_spec.rb
spec/models/publish_services_event_metadata_spec.rb
spec/support/notify_support.rb
spec/support/time_helpers.rb
spec/system/user_visits_events_page_spec.rb
spec/system/visit_index_page_spec.rb

**What?**
When Self Service polls the hub successful and a result is acquired. The app needs to inform the service by emailing members of the team that their certificate has been deployed successfully.
**Why?**
This would inform all service team members and provide a link into the app where they can view the certificate and continue with other activities associated with managing their certificates.
**How?**
Immediately after the in_use_at field has been updated an email would be sent to each team member.

Hub 418 schedule email when certificate is being used by hub

---

.gitignore
README.md
tools/check.rb

- added a first stab of a script which checks whether everything is ok
- it compares the hub-fed-config with the remote config published by the self-service tool
Pre-requisite:
- logged in to AWS using gds-cli, to the account for which we're doing check
To run:
`./check <env> <entity_id>`
e.g.
`./check.rb prod https://www.fitness-to-drive.service.gov.uk/renew`
Ignoring MSA for the moment

Add a script to check integrity when onboarding a new service

---

app/models/change_service_event.rb
app/models/trigger_metadata_event_callback.rb
spec/models/change_service_event_spec.rb

Fix for a bug that was discovered in verify self service which meant when you updated a services metadata (specifically its entity_id) it didn't publish the results to the S3 bucket.  This PR should fix that issue.

Updated the change service event to publish metadata on save.

---

app/views/certificates/new/_msa_cert.html.erb
app/views/certificates/new/_sp_cert.html.erb
app/views/shared/_component_environments.erb
app/views/sp_components/edit.html.erb
app/views/sp_components/new.html.erb

This fixes a bug in Self Service where by clicking on a radio button
label didn't involke the assumed associated radio button

HUB-540 Associated radio buttons with values

---

app/models/polling/scheduler.rb
config/database.yml
config/environments/production.rb
config/environments/test.rb
config/puma.rb
spec/models/polling/scheduler_spec.rb
spec/models/publish_services_event_metadata_spec.rb

**What**
see
https://sentry.tools.signin.service.gov.uk/verify/prod-self-service/issues/4293)
https://sentry.tools.signin.service.gov.uk/verify/prod-self-service/issues/4291
https://sentry.tools.signin.service.gov.uk/verify/prod-self-service/issues/4292
https://sentry.tools.signin.service.gov.uk/verify/prod-self-service/issues/4293
When Rufus-scheduler run a schedule or piece of code, it creates a new thread. Self service app is configured to continue to poll the hub at 15s interval for a maximum of 12 times. During this period it interacts with the self service database and potentially a new thread with a connection to the database. Rufus scheduler also has a `max_work_threads` which is 28 by default.
The Active record database `connection pooling` and Puma web server `thread_count` are …

HUB-515: Connection pool timeout in self service

---

lib/notify/notification.rb
spec/controllers/users_controller_spec.rb

When a user’s password reset is initiated through team member management, the email is delivered to that user with a broken link. 
Discovered that the URL was missing the first part of the address:

HUB-711: Fix broken URL in the password reset email

---

app/controllers/certificates_controller.rb
app/controllers/teams_controller.rb
app/helpers/admin_helper.rb
app/policies/certificates_controller_policy.rb
app/policies/teams_controller_policy.rb
app/views/admin/_certificate.erb
app/views/admin/_msa_component.html.erb
app/views/admin/_service.erb
app/views/admin/_sp_component.html.erb
app/views/admin/_team.erb
app/views/certificates/show.html.erb
app/views/teams/show.html.erb
spec/system/visit_certificate_show_spec.rb
spec/system/visit_team_show_spec.rb

Due to the way it is already set up you cant just jump to a section on the page as that would be an anchor inside an anchor.
Created a show view for the Team and Certificate so they can be viewed individually like we can with the components, this makes it possible to link across the admin pages.
Fixed links between Services and Components
Fixed links between Components and Teams
Fixed links between Components and (Encryption) Certificates
Fixed links between Certificates and Components
Added tests for the new show pages for the Team and Certificate
New show page for Team:
New show page for Certificate:

HUB-713: Fix broken admin links

---

app/assets/stylesheets/_users.scss
app/views/users/show.html.erb

Currently there is no way to remove an admin user (a GDS team user)
This is not right behaviour as the GDS team has users no longer working within GDS and need a way to be removed.
Moved the link outside the conditional statement so its displayed for the admin team
New link added to the admin team users display to remove user:

HUB-712: Add link to remove admin users

---

config/initializers/remote_authenticatable.rb
config/locales/devise.en.yml
lib/auth/authentication_backend.rb
spec/system/visit_sign_in_spec.rb

See: https://govukverify.atlassian.net/browse/HUB-544 and https://govukverify.atlassian.net/browse/HUB-721
We have seen sentry events where a cogito session timeout results in a sentry event, 
example of HUB-721: https://sentry.tools.signin.service.gov.uk/verify/prod-self-service/issues/4702/?query=is%3Aunresolved
HUB-721 is a result of the **15 minutes** of inactivity or **60 minutes** timeout of a users session see below discussion
example of HUB-544: https://sentry.tools.signin.service.gov.uk/verify/prod-self-service/issues/3762/
HUB-544 was found to be as a result of QR code being stale after **3 minutes** so a more specific error is provided see first commit
Discussion at https://gds.slack.com/archives/GLYGVNMJM/p1584103738008300, (attached too)
We should rather log this event as a …

Hub-721: change Cognito expired session sentry error to warnings

---

spec/models/certificate_in_use_event_spec.rb

Some times the order of events happening is not what is expected
But what is really important is that the expected events happened so changing
the the array test from absolute equality to set like equality i.e.
`expect(certificate.events.map(&:class)).to eq [CertificateInUseEvent, CertificateNotificationSentEvent]`
changed to
`expect(certificate.events.map(&:class)).to contain_exactly(CertificateInUseEvent, CertificateNotificationSentEvent)`

BAU: change flaky certificate in use event spec

---

config/initializers/sentry.rb

Set the sentry environment information correctly and tell sentry to run in production, integration and staging.

HUB-733 Disable sentry environment reporting

---

config/initializers/sentry.rb

The rationale for this, is that we currently have verify-frontend https://github.com/alphagov/verify-frontend/blob/a5719acce2f8ddff1a0acbeea64a1062b9ae365e/config/initializers/logging.rb#L21
set up this way, so it should work with self-service as well
The reason for the array was to constraint sentry to run only in
the environment specified. I think we don't need to do this explicitly

HUB-733: Remove environments array

---

app/models/aggregated_event.rb
app/models/new_msa_component_event.rb
app/models/new_service_event.rb
config/locales/en.yml
spec/factories/components.rb
spec/factories/events.rb
spec/factories/service.rb
spec/models/new_msa_component_event_spec.rb
spec/models/new_service_event_spec.rb
spec/models/publish_services_event_metadata_spec.rb
spec/system/visit_msa_component_new_spec.rb
spec/system/visit_service_new_spec.rb

https://govukverify.atlassian.net/browse/HUB-766
- Added validation to the new_msa_component_event when the component is being created
- Fixed existing tests relying on the same entity id across all MSA components, now uses SecureRandom.alphanumeric to generate the entity id
- Created a system test to show that you cannot create a second MSA component with an existing entity id
- Also fixed a error display message.
https://govukverify.atlassian.net/browse/HUB-707
- Removed trailing and leading whitespaces from service/msa entity_id
- Raises an error if there are spaces between the string
- Created system / model test to prove this works
The new validation displays:

HUB-766: Validate & format entity id's

---

app/views/admin/_team.erb

The partial was referring to the instance variable rather than the variable passed into the partial

BAU: Fix admin display tabs that show separated IDP and RP teams

---

app/assets/stylesheets/_users.scss
app/controllers/users_controller.rb
app/models/team.rb
app/policies/users_controller_policy.rb
app/views/admin/_team.erb
app/views/users/index.html.erb
config/initializers/constants/teams.rb
config/locales/en.yml
config/routes.rb
spec/controllers/users_controller_spec.rb
spec/system/visit_users_spec.rb

Added download buttons to collect RP, IDP, ALL emails as CSV for Notify, from self-service.
The first column of each CVS is named email address (with a space) so it’s compatible with Notify.
Rearranged the Team members page to clearly put IDP, RP, OTHER team types into there own lists
It also adds the idasupport email address to each of the csv files that can be generated.
Before: 
After: 
The generated CSV looks like this:

HUB-852: Download buttons to retrieve emails from self-service

---

app/controllers/user_journey_controller.rb
app/helpers/user_journey_helper.rb
app/models/team.rb
app/views/layouts/main_layout.html.erb
app/views/shared/_component_teams.erb
app/views/users/index.html.erb
app/views/users/invite.html.erb
app/views/users/show.html.erb
spec/factories/users.rb
spec/system/visit_msa_component_new_spec.rb
spec/system/visit_sp_component_new_spec.rb
spec/system/visit_users_details_page_spec.rb
spec/system/visit_users_spec.rb

Subsequent to https://github.com/alphagov/verify-self-service/pull/395
Admin users can no longer see and click manage certificate role for idp team users
Remove IDP teams from list on components so you cannot add components to idp teams
Fix the testing suite, the way the initial setup was being done meant that the tests kept getting mixed information
- made clear seperation between the test cases
No longer show the certificate manager role option:

HUB-835: Admin support for IDP & RP teams

---

Dockerfile
run.Dockerfile
test.Dockerfile

We have moved back to using DockerHub rather than GitHub container registry and have to replace our Dockerfiles with arguments using instructions from DockerHub. However, because we're also using oci-build-task now and registry-image rather than docker-image in concourse we also need to supply an IMAGE_ARG instruction so we're speedy.
I've added that in a companion commit over at https://github.com/alphagov/verify-terraform/pull/1457/files

[HUB-841] Use Docker Hub rather than GHCR

---

Dockerfile

`EEXIST: file already exists, symlink '../lib/node_modules/yarn/bin/yarn.js' -> '/usr/bin/yarn'` is causing the pipeline to fail.
I've removed the reference to install yarn for the time being to see if it builds. The setup_10.x script referencing installing yarn but only when flagged by the look of it. I'm assuming the base image already has it and/or it's installed somewhere between but haven't entirely dug down to see.
Signed-off-by: Chris Mills <7100370+chriscoffee@users.noreply.github.com>

[HUB-841] Remove yarn install dependency

---

README.md
app/controllers/support_controller.rb
app/models/user_role_permissions.rb
app/policies/support_controller_policy.rb
app/views/layouts/application.html.erb
app/views/support/index.html.erb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/locales/en.yml
config/routes.rb
pre-commit-local.sh
spec/controllers/support_controller_spec.rb
startup.sh

Added a new static support page to Self-Service instead of redirecting to an external page. The custom page is based on the page that we were redirecting to (https://www.verify.service.gov.uk/support/). The content has been cut down to only include information relevant to RPs or IDPs. A mailto link has been added so RPs and IDPs can find our support email address.
Use the environment variable 'support_email' to get the value for the email. This means the actual email address won't be included in the public repo.
- Added the `view_support` permission set to `true` - this allows all users to view the support page and only logged in users can see the page
- Added the `-d` option to the startup script so the user can run the app with docker without providing input on the console
- Updated …

HUB-981: Add support page with email

---

app/controllers/application_controller.rb
app/controllers/static_controller.rb

Changed from include Pundit to include Pundit::Authorization

BAU: Stop using deprecated include pundit

---

app/controllers/user_journey_controller.rb
app/views/shared/_error_summary.html.erb

Active model errors key changed to Active model error attributes_name
due to upgrade from rails 6.0.5.1 to 6.1.6.1

BAU: Remove deprecation errors

---

Gemfile
Gemfile.lock

Our version of Capybara doesn’t support Puma 6, so downgrading for now so the pipeline could be unblocked for Dockerfile updates

downgrade puma to allow acceptance tests to run
