alphagov/verify-self-service

Dockerfile
- These steps now happen in verify-terraform as part of the verify-self-service pipeline configuration.
=> NDRHGGrk: Update Dockerfile

app/views/home/index.html.erb
A simple change to test that the deployment pipeline will pick up the change and deploy it.
=> NDRHGGrk: Change to Test Deploy Pipeline

.pre-commit-config.yaml, pre-commit.sh, startup.sh
Setup ./pre-commit.sh & ./startup.sh scripts
=> JBGjO9CR: Setup ./pre-commit.sh & ./startup.sh scripts

.travis.yml, Gemfile, Gemfile.lock, lib/tasks/yarn.rake, pre-commit.sh, spec/spec_helper.rb, spec/system/visit_home_controller_spec.rb
Acceptance tests run on travis with JavaScript enabled and disabled.
Co-authored-by: Jamie Maynard <james.maynard@digital.cabinet-office.gov.uk>
=> MITyhlun: Run acceptance tests using travis

db/migrate/20190204113019_create_certificates.rb
=> FIX: Can now run database migration

spec/system/visit_index_page_spec.rb, spec/system/visit_upload_page_spec.rb
Renamed system spec files to match the page they are testing
System test for upload page succesfully submits to the page
=> 3fv3UwKG: Implement system test for certificate submission

lib/tasks/acceptance_tests.rake
co-authored-by: Olakunle Jegede <olakunle.jegede@digital.cabinet-office.gov.uk>
co-authored-by: Rosa Fox <rosa.fox@digital.cabinet-office.gov.uk>
=> omtujEyR: Don't require rspec in prod

manifest-db-migration.yml
=> Add new manifest for secondary app used for running migrations

app/controllers/certificates_controller.rb, app/models/event.rb, app/models/upload_certificate_event.rb, app/views/certificates/upload.html.erb, db/migrate/20190305142449_create_events.rb, db/schema.rb, spec/models/event_spec.rb, spec/models/shared_examples/event.rb, spec/models/upload_certificate_event_spec.rb, spec/rails_helper.rb
Introduces the concept of event sourcing for events that happen on the
self-service application.
More docs to follow.
=> VavuzB9e: Add `Event` and `UploadCertificateEvent`

README.md, doc/adr/0001-record-architecture-decisions.md, doc/adr/0002-use-event-sourcing.md, startup.sh
What:
- Updates the README with some helpful guidance
- Add an ADR for event sourcing
- Add a travis badge
=> gSWSucJ7: document event sourcing

pre-commit.sh
Updated the pre-commit script to also check for `git secrets` in
addition to `pre-commit`. When installed it makes sure the hooks are installed
and installs them if not.
https://github.com/awslabs/git-secrets
=> BAU: Add AWS credentials check

app/models/publish_services_metadata_event.rb
The metadata variable needs to be on the instance.
=> Fix publishing of metadata

app/controllers/components_controller.rb, app/views/layouts/application.html.erb, app/views/layouts/login_signup_layout.html.erb, app/views/layouts/main_layout.html.erb
Created a layout for the main pages - one third, two thirds
Created a layout for the signup/login pages - one half
https://trello.com/c/RBlr4OhF/492-build-the-site-layouts
=> Build the site layouts/template

app/models/user_sign_in_event.rb, app/views/dashboard/show.html.erb, config/initializers/remote_authenticatable.rb, spec/models/user_sign_in_event_spec.rb
Also updated dashboard to show user id
Also added cognito_pool_id to the secrets
Co-Authored-By: Rosa Fox <rosa.fox@digital.cabinet-office.gov.uk>
=> Added user sign in event

app/controllers/application_controller.rb, app/helpers/user_info.rb, app/models/event.rb, app/models/user_sign_in_event.rb, db/migrate/20190724164118_add_user_id_to_events.rb, db/schema.rb, spec/models/new_sp_component_event_spec.rb, spec/models/user_sign_in_event_spec.rb
Co-authored-by: James Maynard <james.maynard@digital.cabinet-office.gov.uk>
Co-authored-by: Olakunle Jegede <olakunle.jegede@digital.cabinet-office.gov.uk>
=> Adding user id to all events

app/models/event.rb, app/views/events/index.html.erb, spec/models/user_sign_in_event_spec.rb
Co-Authored-By: Olakunle Jegede
<olakunle.jegede@digital.cabinet-office.gov.uk>
=> Added user id to events page

doc/adr/0003-use_pundit_for_rbac.md
**What**
Investigate Cognito features and ways to manage to RBAC (Role-based Access Control) and figure out if we can use the built-in features or will have to build something ourselves.
**Why**
So we know whether Cognito provides the functionality which satisfies our requirements.
**What we ended up with**
A description of RBAC provided by a Ruby GEM storing information in Cognito.
=> JDJCScwO - Added ADR for RBAC

app/controllers/sessions_controller.rb, app/models/user_sign_out_event.rb, config/routes.rb, spec/controllers/session_controller_spec.rb, spec/models/user_sign_out_event_spec.rb
**What**
Allow users to log out of their self-service account securely and end the session.
**Why**
Users are likely to expect this feature and we should provide it for security purposes.
We have already made some progress as part of the authentication, therefore this ticket is about validating the logout functionality and adding any tests (if neccessary)
**What we did**
Created a new SignOut event to log when users sign out.  Added related tests.  Confirmed sign out process.
=> eOGBlxNe Added SignOut Event and confirmed tests

app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/views/certificates/list/_certificate_table.html.erb, app/views/certificates/new/_msa_cert.html.erb, app/views/certificates/new/_sp_cert.html.erb, app/views/certificates/status/_certificate_table.html.erb, app/views/dashboard/show.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/events/index.html.erb, app/views/layouts/application.html.erb, app/views/msa_components/_all_msa_components.html.erb, app/views/msa_components/new.html.erb, app/views/msa_components/show.html.erb, app/views/services/index.html.erb, app/views/services/new.html.erb, app/views/shared/_component_certificates.html.erb, app/views/shared/_error_messages.html.erb, app/views/sp_components/_all_sp_components.html.erb, app/views/sp_components/new.html.erb, app/views/sp_components/show.html.erb, package.json, yarn.lock
https://trello.com/c/Dpi1Tadm/494-upgrade-to-design-system-v3
=> Dpi1tadm: upgrade the design system

config/initializers/remote_authenticatable.rb
To help us troubleshoot our AWS deployment.
=> BAU: Add logging to cognito response

lib/tasks/copy_govuk_dependencies.rake
Co-Authored-By: Brendan Butler <brendan.butler@digital.cabinet-office.gov.uk>
=> BAU: Fix precompile task after the Design System upgrade

doc/adr/0003-use-pundit-for-rbac.md
Just added one more line and fixed casing.
Also renamed the file to be consistent with others.
=> BAU: Accept the RBAC ADR

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/msa_components_controller.rb, app/controllers/sp_components_controller.rb, app/models/remote_authenticatable.rb, app/models/user.rb, app/models/user_role_permissions.rb, app/policies/application_policy.rb, app/policies/component_policy.rb, app/policies/new_msa_component_event_policy.rb, app/policies/new_sp_component_event_policy.rb, config/locales/en.yml, spec/controllers/components_controller_spec.rb, spec/controllers/msa_components_controller_spec.rb, spec/controllers/sp_components_controller_spec.rb, spec/factories/users.rb, spec/support/auth_support.rb, spec/support/helpers/session_helpers.rb, spec/system/visit_msa_component_new_spec.rb, spec/system/visit_sp_component_new_spec.rb
Adds in Pundit.  Creates a new User Roles Permission class which maps user roles to permissions in code.
=> 3rmbdDO4 Added in Pundit and defined user roles in code

app/controllers/admin_controller.rb, config/locales/en.yml, config/routes.rb, spec/controllers/admin_controller_spec.rb, spec/system/user_visits_events_page_spec.rb
https://trello.com/c/fxKBjwWI/573-move-all-admin-views-to-admin-path
Moving all views under admin in preperation for creating the user journey
=> fxKBjwWI: Move all current views under admin url

Gemfile, Gemfile.lock, app/controllers/users_controller.rb, app/models/invite_user_form.rb, app/models/user_invited_event.rb, app/models/user_role_permissions.rb, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb, app/views/layouts/main_layout.html.erb, app/views/users/index.erb, app/views/users/invite.erb, config/initializers/constants/roles.rb, config/locales/en.yml, config/routes.rb, config/secrets.yml, spec/controllers/users_controller_spec.rb, spec/factories/users.rb, spec/models/invite_user_form_spec.rb
- added a new pages /users for listing and inviting users
- this PR is only focused on inviting users (not listing them)
- it includes a couple of TODOs which will be tackled later
=> Ability to invite users

app/models/new_team_event.rb
=> Fix typo and appease the linter

config/database.yml, config/puma.rb
Switching from single to cluster mode for Puma to improve the performance
when deployed.
https://puma.io/puma/#Clustered-mode
=> BAU: Improve the performance

config/puma.rb
The app is not happy when preload is active in prod environment
=> BAU: Stop preloading the app

.env.development, .env.test, config/secrets.yml
This is an attempt to debug the app startup a bit more.
Co-authored-by: Olakunle Jegede <olakunle.jegede@digital.cabinet-office.gov.uk>
=> Use fetch to get aws region from environment

db/migrate/20190812105927_add_environment_to_sp_components.rb, db/migrate/20190812110003_add_environment_to_msa_components.rb
Once more unto the breach . ..
=> Adjust previous migrations take 2

app/controllers/profile_controller.rb, lib/auth/cognito_stub_client.rb
Fixed bug when no role is selected
Also removed unused method on the cognito-stub-client
=> BAU Fixed bug when no role is selected

app/controllers/profile_controller.rb, config/initializers/services.rb, lib/auth/cognito_chooser.rb, lib/auth/cognito_stub_client.rb
Using 'false' and 'true' was making my eye twitch . . . .
=> Stop coercing booleans to strings

doc/adr/0004-use-cognito-for-authentication.md
Adding ADR on why we have decided to use AWS Cognito. 
Comments welcome!
=> ADR: Use AWS Cognito for authentication

app/views/msa_components/show.html.erb, app/views/services/list/_services_table.html.erb
https://trello.com/c/NHDnezNg/608-fix-the-accordions-on-the-component-page
=> NHDnezNg: Fix the accordions on the component page

app/controllers/application_controller.rb
Updated the magic to allow for namespaced controllers to be user.
=> Updated check authorization for namespaces

app/views/layouts/application.html.erb
Establish paths for the various Favicon images and fixed 'govuk-logotype-crown.png' not being displayed properly.
=> Restores Favicon to the frontend

lib/storage/storage_registrar.rb
"Access denied" just isn't helpful
=> Set debug log level on aws sdk client

app/views/devise/sessions/_mfa_form.erb
Small PR just to disable to autocomplete on the form.
=> djoEdoCG Disable autocomplete on totp form field

Gemfile, Gemfile.lock, app/controllers/users_controller.rb, app/models/remote_authenticatable.rb, app/models/user.rb, app/views/profile/show.html.erb, app/views/users/index.erb, config/application.rb, config/locales/en.yml, lib/auth/cognito_chooser.rb, lib/auth/cognito_stub_client.rb, lib/auth/jwks_loader.rb, spec/controllers/mfa_controller_spec.rb, spec/controllers/session_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/factories/users.rb, spec/support/helpers/session_helpers.rb, spec/system/sign_out_spec.rb, spec/system/visit_mfa_enrolment_spec.rb, spec/system/visit_sign_in_spec.rb
This commit switches to decoding the JWT from Cognito for building the
user.  In addiition the stub code is updated to to building JWTs and
using those in the stub client.  Tests have also been updated to reflect
the change.
=> XTHIuvEX switched to using JWT for building user

app/models/remote_authenticatable.rb, config/initializers/remote_authenticatable.rb, lib/auth/authenticated_response.rb, lib/auth/authentication_backend.rb, lib/auth/challenge_response.rb
This is the first part of abstracting cognito code in to its own
module.
=> L1oT6Vxf Abstract cognito from the auth flow

spec/acceptance/visit_home_page_acceptance_spec.rb
This is the temporary first step to having a full acceptance test suite.
https://trello.com/c/ELkK8dUG/601-add-acceptance-tests-to-the-pipeline
=> Adjust Home Page acceptance test

app/controllers/users_controller.rb
This was a recommendation following penetration testing - the passwords are now longer and are fully random.
=> mHRKnaGT: Improve strength of temporary passwords

app/controllers/users_controller.rb, app/views/users/index.erb, spec/controllers/users_controller_spec.rb
We no longer need the special team for GDS.
=> BAU: Remove the special GDS team (id 0)

Dockerfile, app/views/layouts/application.html.erb, public/robots.txt
We do not want the Self Service app to be indexed.
https://trello.com/c/y02L98Wo/643-add-robotstxt
=> Disallow all robots

package.json, yarn.lock
Some accessibility fixes between 3.0 and 3.1 were introduced.
=> BAU: Update GOV.UK Frontend to 3.1

lib/auth/jwks_loader.rb
It should have called the `fetch_or_update` method, not just fetch. My bad...
=> Fix the caching

config/application.rb, config/initializers/filter_parameter_logging.rb
We do not want these parameters to be logged anywhere.
https://trello.com/c/8D4e0XJ3/637-filter-out-sensitive-parameters-when-logging
=> Filter sensitive parameters from logs

app/helpers/user_journey_helper.rb, app/models/component.rb, spec/models/component_spec.rb
This will help fix the inconsistent test failures
=> BAU: updating the has_many relationship to sort by created date

app/helpers/user_journey_helper.rb, app/views/user_journey/index.html.erb, config/locales/en.yml, spec/system/visit_index_page_spec.rb
Display the number of certificates expiring on the dashboard as per the prototype
=> rG3kdLG9: Show the number of expiring certificates on dashboard

app/helpers/user_journey_helper.rb, app/views/shared/_user_component_certificates.html.erb, app/views/user_journey/view_certificate.html.erb
Was checking against all signing certificates therefore causing issues to occur when a signing certificate was disabled
=> BAU: only use the enabled signing certificates

app/models/aggregated_event.rb, app/models/certificate_validator.rb, app/models/invite_user_form.rb, app/models/new_msa_component_event.rb, app/models/new_sp_component_event.rb, app/models/toggle_enable_event.rb, app/models/upload_certificate_event.rb, config/locales/en.yml, spec/models/upload_certificate_event_spec.rb
This makes it easier to see what content gets used
🚚 📦 Special delivery for @christopherthomasdesign
=> Localize all error messages

app/controllers/profile_controller.rb, app/models/change_password_form.rb, app/policies/profile_controller_policy.rb, app/views/profile/password_form.html.erb, app/views/profile/show.html.erb, config/locales/en.yml, config/routes.rb, lib/auth/authentication_backend.rb, spec/controllers/profile_controller_spec.rb, spec/factories/users.rb, spec/models/change_password_form.rb
Still to do are tests and localisation
=> KBnecGjV Added first part of password change

app/controllers/sessions_controller.rb, app/controllers/static_controller.rb, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb, app/views/layouts/full_width_layout.html.erb, app/views/layouts/login_signup_layout.html.erb, app/views/static/cookies.html.erb, config/locales/en.yml, config/routes.rb
As part of the preparation for go-live we're adding the Cookies Policy
- created a new static controller for non-authenticated stuff
- renamed the full-width layout
- added a new link to the footer
=> Add cookies policy

app/controllers/password_controller.rb, app/controllers/profile_controller.rb, app/models/change_password_form.rb, app/models/forgotten_password_form.rb, app/models/password_recovery_form.rb, app/policies/password_controller_policy.rb, app/views/devise/sessions/_password_recovery_form.erb, app/views/devise/sessions/new.html.erb, app/views/password/_password_recovery_form.erb, app/views/password/forgot_form.html.erb, app/views/password/password_form.html.erb, app/views/password/user_code.html.erb, app/views/profile/show.html.erb, config/locales/en.yml, config/routes.rb, lib/auth/authentication_backend.rb, spec/controllers/password_controller_spec.rb, spec/controllers/profile_controller_spec.rb, spec/models/forgotten_password_form_spec.rb, spec/models/password_recovery_form_spec.rb
Users should be able to reset their own password.
The forgotten password functionality should be added and user journey build as per the prototype.
=> Fvf3hw password recovery flow

app/controllers/static_controller.rb, app/views/layouts/application.html.erb, app/views/static/privacy.html.erb, config/locales/en.yml, config/routes.rb, spec/system/visit_cookies_page.rb, spec/system/visit_privacy_policy_page.rb
And also added test for cookies policy, removed the
method from the controller as it's not needed and change the links to rails helpers.
Source: https://docs.google.com/document/d/1nV-WvnBHr5c8ZtKSTKeD4fst0ZMZEJacRk04ac35eDc/edit#
=> 2vzM3J3r: Add privacy notice

app/controllers/sessions_controller.rb, app/controllers/teams_controller.rb, app/helpers/error_helper.rb, app/views/certificates/new.html.erb, app/views/devise/sessions/_sign_in_form.erb, app/views/devise/sessions/new.html.erb, app/views/msa_components/new.html.erb, app/views/services/new.html.erb, app/views/shared/_error_summary.html.erb, app/views/sp_components/new.html.erb, app/views/teams/edit.html.erb, spec/controllers/teams_controller_spec.rb
- refactored the method for adding error messages
- updated the existing ones to use the refactored methods
**Before:**
**After:**
=> BAU: Add the design system validation styles on to the login page

app/helpers/user_journey_helper.rb, app/models/component.rb, app/views/shared/_certificate_details.html.erb, app/views/shared/_component_certificate_doc_links.html.erb, app/views/shared/_user_component_certificates.html.erb, app/views/user_journey/before_you_start.html.erb, app/views/user_journey/check_your_certificate.html.erb, app/views/user_journey/confirmation.html.erb, app/views/user_journey/view_certificate.html.erb, config/locales/en.yml
Currently was using a function which did two different things.
Better to use two seperate model methods to make it more clearer when its being used for interpolation or displaying
=> FIX: Use model to display components

app/assets/stylesheets/_user_journey.scss, app/controllers/profile_controller.rb, app/views/profile/show.html.erb, config/locales/en.yml, spec/controllers/profile_controller_spec.rb, spec/system/visit_profile_page_spec.rb
Replaced existing table and fields to match the prototype
Removed old data that was potentially used for testing and that is unnecessary
Localised all the text on the profile page
Added back button on profile page
=>  ZHECKmEx: update profile page

app/views/shared/_certificate_details.html.erb, app/views/user_journey/before_you_start.html.erb, config/locales/en.yml, spec/system/visit_user_journey_upload_certificate_page_spec.rb, spec/system/visit_user_journey_view_certificate_page_spec.rb
Minor grammer changes to be consistent with the prototype
Fix the tests due to these changes
=> wmqZinth: content fixes to be consistent with the prototype

app/controllers/msa_components_controller.rb, app/controllers/sp_components_controller.rb, app/models/delete_component_event.rb, app/policies/component_policy.rb, app/views/admin/_msa_component.html.erb, app/views/admin/_sp_component.html.erb, spec/controllers/msa_components_controller_spec.rb, spec/controllers/sp_components_controller_spec.rb, spec/factories/events.rb, spec/models/delete_component_event_spec.rb
We should have an option to update components:
- delete the component
This should be done through event sourcing by having an update event
=> izwWZKQ Delete component button and support code

app/controllers/users_controller.rb, spec/controllers/users_controller_spec.rb
Trello ticket... https://trello.com/c/v3NbtKCU
=> v3NbtKCU Fix for nil bug when cognito fails to invite user

app/views/profile/show_change_mfa.html.erb, app/views/profile/warn_mfa.html.erb, config/locales/en.yml, spec/system/visit_mfa_preferences_spec.rb
Matched to content given to us by Beth.
=> Updated content for warning page and updated test

app/controllers/static_controller.rb, spec/system/visit_cookies_page_spec.rb, spec/system/visit_privacy_policy_page_spec.rb
Added pundit to the static controller which fixed the issue.
See trello: https://trello.com/c/eqHbVUvF
=> Fix for broken Cookie and Privacy pages

app/controllers/users_controller.rb, app/views/users/invite.html.erb, config/locales/en.yml, spec/controllers/users_controller_spec.rb, spec/system/visit_invite_user_spec.rb
See Trello: https://trello.com/c/J5QJ0lVO
=> Added error style, added test for page

app/controllers/users_controller.rb, app/views/users/invite.html.erb, spec/system/visit_invite_user_spec.rb
Added missing happy path test which might have caught this.
=> Bugfix for broken form submission with missing test

app/views/user_journey/before_you_start.html.erb, app/views/user_journey/confirmation.html.erb, config/locales/en.yml
See Trello Ticket: https://trello.com/c/SU2UNIPJ
=> Some minor content changes as requested

app/controllers/sp_components_controller.rb, app/models/assign_sp_component_to_service_event.rb, app/models/service.rb, app/models/trigger_metadata_event_callback.rb, config/locales/en.yml, spec/controllers/sp_components_controller_spec.rb, spec/models/assign_sp_component_to_service_spec.rb
* AssignSpComponentToServiceEvent should trigger metadata publishing
* Use scopes to determine available services
* Combine two flash messages into one as only one can be displayed at a time anyway
* Include service name in AssignSpComponentToServiceEvent, to aid debugging
=> eq8a6mon: Various clean-up for PR 261

spec/models/assign_msa_component_to_service_spec.rb
=> BAU: Fix the wrong test

app/views/user_journey/index.html.erb, config/locales/en.yml
As per the content review, adding the introductory sentence.
**Before:**
**After:**
=> 33mYwzaj: Add an introductory sentence to the dashboard page

app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb, config/locales/en.yml, spec/system/header_spec.rb
=> Update header in line with prototype

app/controllers/profile_controller.rb, app/models/remote_authenticatable.rb, app/models/update_user_name_event.rb, app/models/update_user_name_form.rb, app/models/user.rb, app/policies/member_policy.rb, app/policies/profile_controller_policy.rb, app/views/profile/show.html.erb, app/views/profile/show_update_name.html.erb, config/locales/en.yml, config/routes.rb, lib/auth/authentication_backend.rb, spec/controllers/profile_controller_spec.rb, spec/system/visit_profile_page_spec.rb, spec/system/visit_profile_update_user_name_spec.rb
Give the ability for users to change there own name
Added new cognito API call update_user_name
Created a new view to change user name
Created a UpdateUserNameEvent
Added controller tests
Added basic system tests
=> Zgolbj2r: enable users to change their name

lib/tasks/check_expiring_certs.rake
- Currently just prints 'Hello World!'.
- Email sending will be implemented at a later date.
- Currently serves as a basic rake task which we will use to test out setting up scheduling with Fargate.
=> Skeleton rake task for email scheduling

app/controllers/password_controller.rb, lib/auth/authentication_backend.rb, lib/notify/notification.rb, spec/controllers/password_controller_spec.rb
A notification email is now sent when user changes/resets their password.
=> EnWrvhcz: Send a notification email when user changes or resets password

app/controllers/msa_components_controller.rb, app/controllers/sp_components_controller.rb, app/models/change_component_event.rb, app/models/healthcheck/storage_check.rb, app/models/new_msa_component_event.rb, app/models/new_sp_component_event.rb, app/models/publish_services_metadata_event.rb, app/views/admin/_publish.erb, app/views/shared/_component_environments.erb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb
These changes are temporary!
Don't merge until these have been reviewed and merged
- https://github.com/alphagov/verify-infrastructure-config/pull/231
- https://github.com/alphagov/verify-infrastructure/pull/348
=> 9lg6CX1O-zdd-add-hub-environment-legacy

Gemfile.lock
Puma has a medium vulnerability. Updating to resolve.
=> CVE-2019-16770: Update vulnerable puma

app/models/trigger_metadata_event_callback.rb
The environment value for services with an msa or sp component
is already avialable no need to request to backend
=> bau: service environment for component type

spec/acceptance/user_journey_spec.rb
This is to undo the last commit which is not needed
=> undo-bau-user-acceptance-test

app/controllers/sessions_controller.rb, spec/controllers/session_controller_spec.rb
Relating to
https://sentry.tools.signin.service.gov.uk/verify/prod-self-service/issues/4140
https://sentry.tools.signin.service.gov.uk/verify/prod-self-service/issues/4141/
=> ZD-3911718: Fix for session controller error

config/initializers/sentry.rb
Remove spaces in sentry env array
=> HUB-733: remove spaces sentry array

run.Dockerfile, startup.sh
This should allow you to spin up and instance of Self Service using Docker.  It sorts out creating, populating and running the database as well as running verify self service.
=> BAU Update Startup to use Docker

app/controllers/admin_controller.rb, app/controllers/teams_controller.rb, app/controllers/user_journey_controller.rb, app/helpers/user_journey_helper.rb, app/models/new_team_event.rb, app/views/admin/_team.erb, app/views/admin/index.html.erb, app/views/layouts/main_layout.html.erb, app/views/teams/new.html.erb, app/views/teams/show.html.erb, app/views/users/index.html.erb, app/views/users/invite.html.erb, app/views/users/show.html.erb, config/initializers/constants/teams.rb, config/locales/en.yml, db/migrate/20210216112936_add_column_team_type_with_values.rb, db/migrate/20210216113138_change_admin_team_type_to_other.rb, db/schema.rb, lib/auth/initial_seeder.rb, lib/data/integrity_checker.rb, spec/controllers/teams_controller_spec.rb, spec/factories/events.rb, spec/factories/teams.rb, spec/factories/users.rb, spec/models/new_team_event_spec.rb, spec/support/helpers/session_helpers.rb, spec/system/visit_index_page_spec.rb, spec/system/visit_team_new_spec.rb, spec/system/visit_users_details_page_spec.rb, spec/system/visit_users_spec.rb
Ticket: https://govukverify.atlassian.net/browse/HUB-835
**_Commit 1_**
- Created two Rails migrations;
1) To add a column 'team_type' to the teams table with a default value of 'rp'
2) Run a second migration to specifically change the 'GDS' admin team to 'team_type' 'other'
- Differentiated between the teams in the admin controller, so they can be passed into the admin views.
- Changed the admin views to display 'RPs' & 'IDPs' under separate tabs.
- Also had to change the titles of the tabs so that they fit on one line
**_Commit 2_**
- Added a dropdown list to new team page to select a team type ('rp', 'idp', 'other)
- Added validation for the team_type field on the new_team_event model to make sure its present
- Fixed a bunch of broken tests due to these changes, amend the factories and …
=> Hub 835 support different team types

app/views/admin/_team.erb
If team doesnt exist it returns nil, therefore breaking the partial
=> BAU: Fix issue with teams being nil

Gemfile.lock
Reverts alphagov/verify-self-service#403
=> Revert "Bump rexml from 3.2.4 to 3.2.5"

run.Dockerfile, test.Dockerfile
This is to fix running locally and also this would probably
fix the broken pipeline
=> BAU: Update dockerfiles

Dockerfile, run.Dockerfile, test.Dockerfile
Changes to fix local running since upgrade to nokogiri 1.13.8
Also update version of node in the Dockerfile
=> BAU: Fix local running
